# This file configures github.com/golangci/golangci-lint.
version: "2"

run:
  tests: true

linters:
  default: none
  enable:
    - bidichk
    - copyloopvar
    - durationcheck
    - gocheckcompilerdirectives
    - govet
    - ineffassign
    - mirror
    - misspell
    - reassign
    - revive  # only certain checks enabled
    - staticcheck
    - unconvert
    - unused
    - usetesting
    - whitespace

# Linters we tried and will not be using:
# - structcheck
# - errcheck
# - contextcheck
# - errchkjson
# - errorlint
# - exhaustive
# - makezero
# - nilerr

settings:
  staticcheck:
    checks:
      # disable Quickfixes
      - "-QF1*"

  revive:
    enable-all-rules: false
    # see https://golangci-lint.run/usage/linters/#revive
    rules:
      - name: receiver-naming
        severity: warning
        disabled: false
        exclude:
          - ""

exclusions:
  generated: lax
  paths:
    - core/genesis_alloc.go
    - third_party$
    - builtin$
    - examples$

formatters:
  enable:
    - goimports

  settings:
    gofmt:
      simplify: true
