# This file configures github.com/golangci/golangci-lint.

run:
  timeout: 20m
  tests: true
  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true
  skip-files:
    - core/genesis_alloc.go
    - gen_.*.go
    - .*_gen.go

linters:
  disable-all: true
  enable:
    - deadcode
    - goconst
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    # - staticcheck
    - unconvert
    # - unused
    - varcheck

linters-settings:
  gofmt:
    simplify: true
    auto-fix: false
  goconst:
    min-len: 3 # minimum length of string constant
    min-occurrences: 2 # minimum number of occurrences

  gocritic:
    # Which checks should be enabled; can't be combined with 'disabled-checks';
    # See https://go-critic.github.io/overview#checks-overview
    # To check which checks are enabled run `GL_DEBUG=gocritic ./build/bin/golangci-lint run`
    # By default list of stable checks is used.
    enabled-checks:
      - badLock
      - filepathJoin	
      - sortSlice
      - sprintfQuotedString
      - syncMapLoadAndDelete
      - weakCond
      - boolExprSimplify
      - httpNoBody
      - ioutilDeprecated
      - nestingReduce
      - preferFilepathJoin
      - redundantSprint
      - stringConcatSimplify
      - timeExprSimplify
      - typeAssertChain
      - yodaStyleExpr
      - truncateCmp
      - equalFold
      - preferDecodeRune
      - preferFprint
      - preferStringWriter
      - preferWriteByte
      - sliceClear
      #- ruleguard

    # Which checks should be disabled; can't be combined with 'enabled-checks'; default is empty
    disabled-checks:
      - regexpMust
      - exitAfterDefer
      - dupBranchBody
      - singleCaseSwitch
      - unlambda
      - captLocal
      - commentFormatting
      - ifElseChain
      - importShadow
      - builtinShadow

    # Enable multiple checks by tags, run `GL_DEBUG=gocritic golangci-lint run` to see all tags and checks.
    # Empty list by default. See https://github.com/go-critic/go-critic#usage -> section "Tags".
    enabled-tags:
      - performance
      - diagnostic
      - opinionated
      - style
    disabled-tags:
      - experimental
  govet:
    disable:
      - deepequalerrors
      - fieldalignment
      - shadow
      - unsafeptr

issues:
  exclude-rules:
    - path: crypto/blake2b/
      linters:
        - deadcode
    - path: crypto/bn256/cloudflare
      linters:
        - deadcode
    - path: p2p/discv5/
      linters:
        - deadcode
    - path: core/vm/instructions_test.go
      linters:
        - goconst
    - path: cmd/faucet/
      linters:
        - deadcode
    # Exclude some linters from running on tests files.
    - path: test\.go
      linters:
        - gosec
        - unused
        - deadcode
        - gocritic
    - path: cmd/devp2p
      linters:
        - gosec
        - unused
        - deadcode
        - gocritic
    - path: metrics/sample\.go
      linters:
        - gosec
        - gocritic
    - path: p2p/simulations
      linters:
        - gosec
        - gocritic
