version: 1

project_name: mev-commit-geth

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm64
    dir: ./external/geth
    main: ./cmd/geth
    binary: "{{ .ProjectName }}"

archives:
  - format: tar.gz
    name_template: >-
      {{- .Binary }}_
      {{- if .IsSnapshot }}{{ .ShortCommit }}_
      {{- else }}{{ .Version }}_
      {{ end }}
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}
      {{- end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - src: ./external/geth/geth-poa/entrypoint.sh
        dst: ./
        strip_parent: true
      - src: ./external/geth/geth-poa/genesis.json
        dst: ./
        strip_parent: true
      - src: ./external/geth/geth-poa/util/deploy_create2.sh
        dst: ./
        strip_parent: true
      - src: ./external/geth/geth-poa/signer-node*/**/*
        dst: ./
        strip_parent: false

checksum:
  name_template: >-
    {{ .ProjectName }}_
    {{- if .IsSnapshot }}{{ .ShortCommit }}
    {{- else }}{{ .Version }}
    {{- end -}}
    _checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
