"default": true
"MD001": false
"MD004": false
"MD007":
  "indent": 4
"MD013": false
"MD024":
  "siblings_only": true
"MD025": false
"MD026":
  "punctuation": ".;:"
"MD029": false
"MD033": false
"MD034": false
"MD036": false
"MD040": false
"MD041": false
"MD051": false
"MD049":
  "style": "asterisk"
"no-hard-tabs": false
