FROM golang:1.10-alpine as builder

RUN apk add --no-cache make gcc musl-dev linux-headers

ADD . /tomochain
RUN cd /tomochain && make bootnode

FROM alpine:latest

LABEL maintainer="etienne@tomochain.com"

WORKDIR /tomochain

COPY --from=builder /tomochain/build/bin/bootnode /usr/local/bin/bootnode

RUN chmod +x /usr/local/bin/bootnode

EXPOSE 30301

ENTRYPOINT ["/usr/local/bin/bootnode"]

CMD ["--help"]
