FROM alpine:3.14

ARG BOR_DIR=/var/lib/bor
ENV BOR_DIR=$BOR_DIR

RUN apk add --no-cache ca-certificates && \
    mkdir -p ${BOR_DIR}

WORKDIR ${BOR_DIR}
COPY bor /usr/bin/
COPY builder/files/genesis-mainnet-v1.json ${BOR_DIR}
COPY builder/files/genesis-testnet-v4.json ${BOR_DIR}
RUN groupadd -g 10137 bor \
    && useradd -u 10137 --no-log-init --create-home -r -g bor bor \
    && chown -R bor:bor ${BOR_DIR}

USER bor

EXPOSE 8545 8546 8547 30303 30303/udp
ENTRYPOINT ["bor"]
