FROM dmanov/go-ethereum:dev-latest

COPY devnet /root/.ethereum

CMD [
  "--dev",
  "--http",
  "--http.addr", "0.0.0.0",
  "--http.api", "eth,net,web3,personal",
  "--allow-insecure-unlock",
  "--verbosity", "3"
]
