FROM golang:1.23-alpine AS builder

RUN apk add --no-cache make gcc musl-dev linux-headers

ADD . /XDPoSChain
RUN cd /XDPoSChain && make bootnode

RUN chmod +x /XDPoSChain/build/bin/bootnode

FROM alpine:latest

LABEL maintainer="etienne@XDPoSChain.com"

WORKDIR /XDPoSChain

COPY --from=builder /XDPoSChain/build/bin/bootnode /usr/local/bin/bootnode

COPY docker/bootnode ./

EXPOSE 30301

ENTRYPOINT ["./entrypoint.sh"]

CMD ["-verbosity", "6", "-nodekey", "bootnode.key", "--addr", ":30301"]
