# https://docs.netlify.com/integrations/frameworks/next-js/incremental-static-regeneration/

[functions]
  included_files = ["src/**"]

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://matomo.ethereum.org"
