// Code generated by core/vm/gen; DO NOT EDIT.

package vm

import (
	"fmt"

	"github.com/ethereum/go-ethereum/common/math"
	"github.com/ethereum/go-ethereum/core/tracing"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/ethereum/go-ethereum/params"
)

// execUntraced is the generated, tracing-free interpreter fast path. Hot,
// fork-stable opcodes are inlined with their static gas and stack bounds baked
// in. Fork-invariant cold ops (KECCAK256/MLOAD/MSTORE/MSTORE8) call their
// handler and gas functions directly by name. Everything fork-varying is
// dispatched through the active per-fork table in the default case. EVM.Run
// selects this path when no tracer is configured.
func (evm *EVM) execUntraced(scope *ScopeContext) (ret []byte, err error) {
	var (
		contract  = scope.Contract
		mem       = scope.Memory
		stack     = scope.Stack
		table     = evm.table
		rules     = evm.chainRules
		isEIP4762 = rules.IsEIP4762
		pc        = uint64(0)
		res       []byte
	)
	_ = mem
	_ = rules
	_ = isEIP4762
	_ = table
mainLoop:
	for {
		if isEIP4762 && !contract.IsDeployment && !contract.IsSystemCall {
			contractAddr := contract.Address()
			consumed, wanted := evm.TxContext.AccessEvents.CodeChunksRangeGas(contractAddr, pc, 1, uint64(len(contract.Code)), false, contract.Gas.RegularGas)
			contract.chargeRegular(consumed, evm.Config.Tracer, tracing.GasChangeWitnessCodeChunk)
			if consumed < wanted {
				return nil, ErrOutOfGas
			}
		}
		op := contract.GetOp(pc)
		switch op {
		case ADD:
			if sLen := stack.len(); sLen < 2 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 2}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.top--
			stack.size--
			x := &stack.inner.data[stack.inner.top]
			y := &stack.inner.data[stack.inner.top-1]
			y.Add(x, y)
			pc++
			continue mainLoop

		case MUL:
			if sLen := stack.len(); sLen < 2 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 2}
			}
			if contract.Gas.RegularGas < 5 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 5
			stack.inner.top--
			stack.size--
			x := &stack.inner.data[stack.inner.top]
			y := &stack.inner.data[stack.inner.top-1]
			y.Mul(x, y)
			pc++
			continue mainLoop

		case SUB:
			if sLen := stack.len(); sLen < 2 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 2}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.top--
			stack.size--
			x := &stack.inner.data[stack.inner.top]
			y := &stack.inner.data[stack.inner.top-1]
			y.Sub(x, y)
			pc++
			continue mainLoop

		case DIV:
			if sLen := stack.len(); sLen < 2 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 2}
			}
			if contract.Gas.RegularGas < 5 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 5
			stack.inner.top--
			stack.size--
			x := &stack.inner.data[stack.inner.top]
			y := &stack.inner.data[stack.inner.top-1]
			y.Div(x, y)
			pc++
			continue mainLoop

		case SDIV:
			if sLen := stack.len(); sLen < 2 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 2}
			}
			if contract.Gas.RegularGas < 5 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 5
			stack.inner.top--
			stack.size--
			x := &stack.inner.data[stack.inner.top]
			y := &stack.inner.data[stack.inner.top-1]
			y.SDiv(x, y)
			pc++
			continue mainLoop

		case MOD:
			if sLen := stack.len(); sLen < 2 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 2}
			}
			if contract.Gas.RegularGas < 5 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 5
			stack.inner.top--
			stack.size--
			x := &stack.inner.data[stack.inner.top]
			y := &stack.inner.data[stack.inner.top-1]
			y.Mod(x, y)
			pc++
			continue mainLoop

		case SMOD:
			if sLen := stack.len(); sLen < 2 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 2}
			}
			if contract.Gas.RegularGas < 5 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 5
			stack.inner.top--
			stack.size--
			x := &stack.inner.data[stack.inner.top]
			y := &stack.inner.data[stack.inner.top-1]
			y.SMod(x, y)
			pc++
			continue mainLoop

		case ADDMOD:
			if sLen := stack.len(); sLen < 3 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 3}
			}
			if contract.Gas.RegularGas < 8 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 8
			stack.inner.top -= 2
			stack.size -= 2
			x := &stack.inner.data[stack.inner.top+1]
			y := &stack.inner.data[stack.inner.top]
			z := &stack.inner.data[stack.inner.top-1]
			z.AddMod(x, y, z)
			pc++
			continue mainLoop

		case MULMOD:
			if sLen := stack.len(); sLen < 3 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 3}
			}
			if contract.Gas.RegularGas < 8 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 8
			stack.inner.top -= 2
			stack.size -= 2
			x := &stack.inner.data[stack.inner.top+1]
			y := &stack.inner.data[stack.inner.top]
			z := &stack.inner.data[stack.inner.top-1]
			z.MulMod(x, y, z)
			pc++
			continue mainLoop

		case SIGNEXTEND:
			if sLen := stack.len(); sLen < 2 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 2}
			}
			if contract.Gas.RegularGas < 5 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 5
			stack.inner.top--
			stack.size--
			back := &stack.inner.data[stack.inner.top]
			num := &stack.inner.data[stack.inner.top-1]
			num.ExtendSign(num, back)
			pc++
			continue mainLoop

		case LT:
			if sLen := stack.len(); sLen < 2 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 2}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.top--
			stack.size--
			x := &stack.inner.data[stack.inner.top]
			y := &stack.inner.data[stack.inner.top-1]
			if x.Lt(y) {
				y.SetOne()
			} else {
				y.Clear()
			}
			pc++
			continue mainLoop

		case GT:
			if sLen := stack.len(); sLen < 2 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 2}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.top--
			stack.size--
			x := &stack.inner.data[stack.inner.top]
			y := &stack.inner.data[stack.inner.top-1]
			if x.Gt(y) {
				y.SetOne()
			} else {
				y.Clear()
			}
			pc++
			continue mainLoop

		case SLT:
			if sLen := stack.len(); sLen < 2 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 2}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.top--
			stack.size--
			x := &stack.inner.data[stack.inner.top]
			y := &stack.inner.data[stack.inner.top-1]
			if x.Slt(y) {
				y.SetOne()
			} else {
				y.Clear()
			}
			pc++
			continue mainLoop

		case SGT:
			if sLen := stack.len(); sLen < 2 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 2}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.top--
			stack.size--
			x := &stack.inner.data[stack.inner.top]
			y := &stack.inner.data[stack.inner.top-1]
			if x.Sgt(y) {
				y.SetOne()
			} else {
				y.Clear()
			}
			pc++
			continue mainLoop

		case EQ:
			if sLen := stack.len(); sLen < 2 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 2}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.top--
			stack.size--
			x := &stack.inner.data[stack.inner.top]
			y := &stack.inner.data[stack.inner.top-1]
			if x.Eq(y) {
				y.SetOne()
			} else {
				y.Clear()
			}
			pc++
			continue mainLoop

		case ISZERO:
			if sLen := stack.len(); sLen < 1 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 1}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			x := scope.Stack.peek()
			if x.IsZero() {
				x.SetOne()
			} else {
				x.Clear()
			}
			pc++
			continue mainLoop

		case AND:
			if sLen := stack.len(); sLen < 2 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 2}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.top--
			stack.size--
			x := &stack.inner.data[stack.inner.top]
			y := &stack.inner.data[stack.inner.top-1]
			y.And(x, y)
			pc++
			continue mainLoop

		case OR:
			if sLen := stack.len(); sLen < 2 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 2}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.top--
			stack.size--
			x := &stack.inner.data[stack.inner.top]
			y := &stack.inner.data[stack.inner.top-1]
			y.Or(x, y)
			pc++
			continue mainLoop

		case XOR:
			if sLen := stack.len(); sLen < 2 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 2}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.top--
			stack.size--
			x := &stack.inner.data[stack.inner.top]
			y := &stack.inner.data[stack.inner.top-1]
			y.Xor(x, y)
			pc++
			continue mainLoop

		case NOT:
			if sLen := stack.len(); sLen < 1 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 1}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			x := scope.Stack.peek()
			x.Not(x)
			pc++
			continue mainLoop

		case BYTE:
			if sLen := stack.len(); sLen < 2 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 2}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.top--
			stack.size--
			th := &stack.inner.data[stack.inner.top]
			val := &stack.inner.data[stack.inner.top-1]
			val.Byte(th)
			pc++
			continue mainLoop

		case SHL:
			if rules.IsConstantinople {
				if sLen := stack.len(); sLen < 2 {
					return nil, &ErrStackUnderflow{stackLen: sLen, required: 2}
				}
				if contract.Gas.RegularGas < 3 {
					return nil, ErrOutOfGas
				}
				contract.Gas.RegularGas -= 3
				stack.inner.top--
				stack.size--
				shift := &stack.inner.data[stack.inner.top]
				value := &stack.inner.data[stack.inner.top-1]
				if shift.LtUint64(256) {
					value.Lsh(value, uint(shift.Uint64()))
				} else {
					value.Clear()
				}
				pc++
				continue mainLoop

			}
			res, err = opUndefined(&pc, evm, scope)
			break mainLoop
		case SHR:
			if rules.IsConstantinople {
				if sLen := stack.len(); sLen < 2 {
					return nil, &ErrStackUnderflow{stackLen: sLen, required: 2}
				}
				if contract.Gas.RegularGas < 3 {
					return nil, ErrOutOfGas
				}
				contract.Gas.RegularGas -= 3
				stack.inner.top--
				stack.size--
				shift := &stack.inner.data[stack.inner.top]
				value := &stack.inner.data[stack.inner.top-1]
				if shift.LtUint64(256) {
					value.Rsh(value, uint(shift.Uint64()))
				} else {
					value.Clear()
				}
				pc++
				continue mainLoop

			}
			res, err = opUndefined(&pc, evm, scope)
			break mainLoop
		case SAR:
			if rules.IsConstantinople {
				if sLen := stack.len(); sLen < 2 {
					return nil, &ErrStackUnderflow{stackLen: sLen, required: 2}
				}
				if contract.Gas.RegularGas < 3 {
					return nil, ErrOutOfGas
				}
				contract.Gas.RegularGas -= 3
				stack.inner.top--
				stack.size--
				shift := &stack.inner.data[stack.inner.top]
				value := &stack.inner.data[stack.inner.top-1]
				if shift.GtUint64(256) {
					if value.Sign() >= 0 {
						value.Clear()
					} else {

						value.SetAllOne()
					}
					pc++
					continue mainLoop
				}
				n := uint(shift.Uint64())
				value.SRsh(value, n)
				pc++
				continue mainLoop

			}
			res, err = opUndefined(&pc, evm, scope)
			break mainLoop
		case CLZ:
			if rules.IsOsaka {
				if sLen := stack.len(); sLen < 1 {
					return nil, &ErrStackUnderflow{stackLen: sLen, required: 1}
				}
				if contract.Gas.RegularGas < 5 {
					return nil, ErrOutOfGas
				}
				contract.Gas.RegularGas -= 5
				x := scope.Stack.peek()
				x.SetUint64(256 - uint64(x.BitLen()))
				pc++
				continue mainLoop

			}
			res, err = opUndefined(&pc, evm, scope)
			break mainLoop
		case KECCAK256:
			if sLen := stack.len(); sLen < 2 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 2}
			}
			if contract.Gas.RegularGas < 30 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 30
			switch {
			default:
				if evm.Config.EnablePreimageRecording {
					break
				}
				off := scope.Stack.back(0)
				sz := scope.Stack.back(1)
				if off[1]|off[2]|off[3] != 0 || sz[1]|sz[2]|sz[3] != 0 {
					break
				}
				size := sz[0]
				if size == 0 || size > 512 {
					break
				}
				store := scope.Memory.store
				if uint64(len(store)) < size || off[0] > uint64(len(store))-size {
					break
				}
				cost := ((size + 31) / 32) * params.Keccak256WordGas
				if contract.Gas.RegularGas < cost {
					break
				}
				contract.Gas.RegularGas -= cost
				o := off[0]
				scope.Stack.drop()
				hash := crypto.Keccak256Hash(store[o : o+size])
				sz.SetBytes(hash[:])
				pc++
				continue mainLoop

			}
			var memorySize uint64
			{
				memSize, overflow := memoryKeccak256(stack)
				if overflow {
					return nil, ErrGasUintOverflow
				}
				if memorySize, overflow = math.SafeMul(toWordSize(memSize), 32); overflow {
					return nil, ErrGasUintOverflow
				}
			}
			var dynamicCost GasCosts
			dynamicCost, err = gasKeccak256(evm, contract, stack, mem, memorySize)
			if err != nil {
				return nil, fmt.Errorf("%w: %v", ErrOutOfGas, err)
			}
			if contract.Gas.RegularGas < dynamicCost.RegularGas {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= dynamicCost.RegularGas
			if memorySize > 0 {
				mem.Resize(memorySize)
			}
			res, err = opKeccak256(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			pc++
			continue mainLoop
		case POP:
			if sLen := stack.len(); sLen < 1 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 1}
			}
			if contract.Gas.RegularGas < 2 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 2
			scope.Stack.drop()
			pc++
			continue mainLoop

		case MLOAD:
			if sLen := stack.len(); sLen < 1 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 1}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			switch {
			default:
				v := scope.Stack.peek()
				if v[1]|v[2]|v[3] != 0 {
					break
				}
				store := scope.Memory.store
				if uint64(len(store)) < 32 || v[0] > uint64(len(store))-32 {
					break
				}
				off := v[0]
				v.SetBytes(store[off : off+32])
				pc++
				continue mainLoop

			}
			var memorySize uint64
			{
				memSize, overflow := memoryMLoad(stack)
				if overflow {
					return nil, ErrGasUintOverflow
				}
				if memorySize, overflow = math.SafeMul(toWordSize(memSize), 32); overflow {
					return nil, ErrGasUintOverflow
				}
			}
			var dynamicCost GasCosts
			dynamicCost, err = gasMLoad(evm, contract, stack, mem, memorySize)
			if err != nil {
				return nil, fmt.Errorf("%w: %v", ErrOutOfGas, err)
			}
			if contract.Gas.RegularGas < dynamicCost.RegularGas {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= dynamicCost.RegularGas
			if memorySize > 0 {
				mem.Resize(memorySize)
			}
			res, err = opMload(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			pc++
			continue mainLoop
		case MSTORE:
			if sLen := stack.len(); sLen < 2 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 2}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			switch {
			default:
				off := scope.Stack.back(0)
				if off[1]|off[2]|off[3] != 0 {
					break
				}
				store := scope.Memory.store
				if uint64(len(store)) < 32 || off[0] > uint64(len(store))-32 {
					break
				}
				o := off[0]
				val := scope.Stack.back(1)
				scope.Stack.drop()
				scope.Stack.drop()
				scope.Memory.Set32(o, val)
				pc++
				continue mainLoop

			}
			var memorySize uint64
			{
				memSize, overflow := memoryMStore(stack)
				if overflow {
					return nil, ErrGasUintOverflow
				}
				if memorySize, overflow = math.SafeMul(toWordSize(memSize), 32); overflow {
					return nil, ErrGasUintOverflow
				}
			}
			var dynamicCost GasCosts
			dynamicCost, err = gasMStore(evm, contract, stack, mem, memorySize)
			if err != nil {
				return nil, fmt.Errorf("%w: %v", ErrOutOfGas, err)
			}
			if contract.Gas.RegularGas < dynamicCost.RegularGas {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= dynamicCost.RegularGas
			if memorySize > 0 {
				mem.Resize(memorySize)
			}
			res, err = opMstore(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			pc++
			continue mainLoop
		case MSTORE8:
			if sLen := stack.len(); sLen < 2 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 2}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			switch {
			default:
				off := scope.Stack.back(0)
				if off[1]|off[2]|off[3] != 0 {
					break
				}
				store := scope.Memory.store
				if off[0] >= uint64(len(store)) {
					break
				}
				val := scope.Stack.back(1)
				scope.Stack.drop()
				scope.Stack.drop()
				store[off[0]] = byte(val[0])
				pc++
				continue mainLoop

			}
			var memorySize uint64
			{
				memSize, overflow := memoryMStore8(stack)
				if overflow {
					return nil, ErrGasUintOverflow
				}
				if memorySize, overflow = math.SafeMul(toWordSize(memSize), 32); overflow {
					return nil, ErrGasUintOverflow
				}
			}
			var dynamicCost GasCosts
			dynamicCost, err = gasMStore8(evm, contract, stack, mem, memorySize)
			if err != nil {
				return nil, fmt.Errorf("%w: %v", ErrOutOfGas, err)
			}
			if contract.Gas.RegularGas < dynamicCost.RegularGas {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= dynamicCost.RegularGas
			if memorySize > 0 {
				mem.Resize(memorySize)
			}
			res, err = opMstore8(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			pc++
			continue mainLoop
		case JUMP:
			if sLen := stack.len(); sLen < 1 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 1}
			}
			if contract.Gas.RegularGas < 8 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 8
			if evm.abort.Load() {
				res, err = nil, errStopToken
				break mainLoop
			}
			pos := scope.Stack.pop1()
			if !scope.Contract.validJumpdest(pos) {
				res, err = nil, ErrInvalidJump
				break mainLoop
			}
			pc = pos.Uint64() - 1
			pc++
			continue mainLoop

		case JUMPI:
			if sLen := stack.len(); sLen < 2 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 2}
			}
			if contract.Gas.RegularGas < 10 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 10
			if evm.abort.Load() {
				res, err = nil, errStopToken
				break mainLoop
			}
			stack.inner.top -= 2
			stack.size -= 2
			pos := &stack.inner.data[stack.inner.top+1]
			cond := &stack.inner.data[stack.inner.top]
			if !cond.IsZero() {
				if !scope.Contract.validJumpdest(pos) {
					res, err = nil, ErrInvalidJump
					break mainLoop
				}
				pc = pos.Uint64() - 1
			}
			pc++
			continue mainLoop

		case PC:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 2 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 2
			stack.inner.top++
			stack.size++
			elem := &stack.inner.data[stack.inner.top-1]
			elem.SetUint64(pc)
			pc++
			continue mainLoop

		case MSIZE:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 2 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 2
			stack.inner.top++
			stack.size++
			elem := &stack.inner.data[stack.inner.top-1]
			elem.SetUint64(uint64(scope.Memory.Len()))
			pc++
			continue mainLoop

		case JUMPDEST:
			if contract.Gas.RegularGas < 1 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 1
			pc++
			continue mainLoop

		case PUSH0:
			if rules.IsShanghai {
				if sLen := stack.len(); sLen > 1023 {
					return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
				}
				if contract.Gas.RegularGas < 2 {
					return nil, ErrOutOfGas
				}
				contract.Gas.RegularGas -= 2
				stack.inner.top++
				stack.size++
				elem := &stack.inner.data[stack.inner.top-1]
				elem.Clear()
				pc++
				continue mainLoop

			}
			res, err = opUndefined(&pc, evm, scope)
			break mainLoop
		case PUSH1:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			codeLen := uint64(len(scope.Contract.Code))
			stack.inner.top++
			stack.size++
			elem := &stack.inner.data[stack.inner.top-1]
			pc += 1
			if pc < codeLen {
				elem.SetUint64(uint64(scope.Contract.Code[pc]))
			} else {
				elem.Clear()
			}
			pc++
			continue mainLoop

		case PUSH2:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			codeLen := uint64(len(scope.Contract.Code))
			stack.inner.top++
			stack.size++
			elem := &stack.inner.data[stack.inner.top-1]
			if pc+2 < codeLen {
				elem.SetBytes2(scope.Contract.Code[pc+1 : pc+3])
			} else if pc+1 < codeLen {
				elem.SetUint64(uint64(scope.Contract.Code[pc+1]) << 8)
			} else {
				elem.Clear()
			}
			pc += 2
			pc++
			continue mainLoop

		case PUSH3:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+3)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 3 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 3
			pc++
			continue mainLoop

		case PUSH4:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+4)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 4 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 4
			pc++
			continue mainLoop

		case PUSH5:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+5)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 5 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 5
			pc++
			continue mainLoop

		case PUSH6:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+6)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 6 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 6
			pc++
			continue mainLoop

		case PUSH7:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+7)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 7 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 7
			pc++
			continue mainLoop

		case PUSH8:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+8)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 8 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 8
			pc++
			continue mainLoop

		case PUSH9:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+9)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 9 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 9
			pc++
			continue mainLoop

		case PUSH10:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+10)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 10 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 10
			pc++
			continue mainLoop

		case PUSH11:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+11)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 11 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 11
			pc++
			continue mainLoop

		case PUSH12:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+12)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 12 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 12
			pc++
			continue mainLoop

		case PUSH13:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+13)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 13 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 13
			pc++
			continue mainLoop

		case PUSH14:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+14)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 14 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 14
			pc++
			continue mainLoop

		case PUSH15:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+15)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 15 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 15
			pc++
			continue mainLoop

		case PUSH16:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+16)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 16 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 16
			pc++
			continue mainLoop

		case PUSH17:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+17)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 17 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 17
			pc++
			continue mainLoop

		case PUSH18:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+18)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 18 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 18
			pc++
			continue mainLoop

		case PUSH19:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+19)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 19 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 19
			pc++
			continue mainLoop

		case PUSH20:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+20)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 20 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 20
			pc++
			continue mainLoop

		case PUSH21:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+21)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 21 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 21
			pc++
			continue mainLoop

		case PUSH22:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+22)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 22 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 22
			pc++
			continue mainLoop

		case PUSH23:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+23)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 23 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 23
			pc++
			continue mainLoop

		case PUSH24:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+24)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 24 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 24
			pc++
			continue mainLoop

		case PUSH25:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+25)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 25 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 25
			pc++
			continue mainLoop

		case PUSH26:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+26)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 26 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 26
			pc++
			continue mainLoop

		case PUSH27:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+27)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 27 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 27
			pc++
			continue mainLoop

		case PUSH28:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+28)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 28 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 28
			pc++
			continue mainLoop

		case PUSH29:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+29)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 29 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 29
			pc++
			continue mainLoop

		case PUSH30:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+30)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 30 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 30
			pc++
			continue mainLoop

		case PUSH31:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+31)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 31 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 31
			pc++
			continue mainLoop

		case PUSH32:
			if sLen := stack.len(); sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			if isEIP4762 {
				res, err = table[op].execute(&pc, evm, scope)
				if err != nil {
					break mainLoop
				}
				pc++
				continue mainLoop
			}
			var (
				codeLen = len(scope.Contract.Code)
				start   = min(codeLen, int(pc+1))
				end     = min(codeLen, start+32)
			)
			stack.inner.top++
			stack.size++
			a := &stack.inner.data[stack.inner.top-1]
			a.SetBytes(scope.Contract.Code[start:end])
			if missing := 32 - (end - start); missing > 0 {
				a.Lsh(a, uint(8*missing))
			}
			pc += 32
			pc++
			continue mainLoop

		case DUP1:
			if sLen := stack.len(); sLen < 1 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 1}
			} else if sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size] = stack.inner.data[stack.bottom+stack.size-1]
			stack.size++
			stack.inner.top++
			pc++
			continue mainLoop

		case DUP2:
			if sLen := stack.len(); sLen < 2 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 2}
			} else if sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size] = stack.inner.data[stack.bottom+stack.size-2]
			stack.size++
			stack.inner.top++
			pc++
			continue mainLoop

		case DUP3:
			if sLen := stack.len(); sLen < 3 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 3}
			} else if sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size] = stack.inner.data[stack.bottom+stack.size-3]
			stack.size++
			stack.inner.top++
			pc++
			continue mainLoop

		case DUP4:
			if sLen := stack.len(); sLen < 4 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 4}
			} else if sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size] = stack.inner.data[stack.bottom+stack.size-4]
			stack.size++
			stack.inner.top++
			pc++
			continue mainLoop

		case DUP5:
			if sLen := stack.len(); sLen < 5 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 5}
			} else if sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size] = stack.inner.data[stack.bottom+stack.size-5]
			stack.size++
			stack.inner.top++
			pc++
			continue mainLoop

		case DUP6:
			if sLen := stack.len(); sLen < 6 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 6}
			} else if sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size] = stack.inner.data[stack.bottom+stack.size-6]
			stack.size++
			stack.inner.top++
			pc++
			continue mainLoop

		case DUP7:
			if sLen := stack.len(); sLen < 7 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 7}
			} else if sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size] = stack.inner.data[stack.bottom+stack.size-7]
			stack.size++
			stack.inner.top++
			pc++
			continue mainLoop

		case DUP8:
			if sLen := stack.len(); sLen < 8 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 8}
			} else if sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size] = stack.inner.data[stack.bottom+stack.size-8]
			stack.size++
			stack.inner.top++
			pc++
			continue mainLoop

		case DUP9:
			if sLen := stack.len(); sLen < 9 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 9}
			} else if sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size] = stack.inner.data[stack.bottom+stack.size-9]
			stack.size++
			stack.inner.top++
			pc++
			continue mainLoop

		case DUP10:
			if sLen := stack.len(); sLen < 10 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 10}
			} else if sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size] = stack.inner.data[stack.bottom+stack.size-10]
			stack.size++
			stack.inner.top++
			pc++
			continue mainLoop

		case DUP11:
			if sLen := stack.len(); sLen < 11 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 11}
			} else if sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size] = stack.inner.data[stack.bottom+stack.size-11]
			stack.size++
			stack.inner.top++
			pc++
			continue mainLoop

		case DUP12:
			if sLen := stack.len(); sLen < 12 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 12}
			} else if sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size] = stack.inner.data[stack.bottom+stack.size-12]
			stack.size++
			stack.inner.top++
			pc++
			continue mainLoop

		case DUP13:
			if sLen := stack.len(); sLen < 13 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 13}
			} else if sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size] = stack.inner.data[stack.bottom+stack.size-13]
			stack.size++
			stack.inner.top++
			pc++
			continue mainLoop

		case DUP14:
			if sLen := stack.len(); sLen < 14 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 14}
			} else if sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size] = stack.inner.data[stack.bottom+stack.size-14]
			stack.size++
			stack.inner.top++
			pc++
			continue mainLoop

		case DUP15:
			if sLen := stack.len(); sLen < 15 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 15}
			} else if sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size] = stack.inner.data[stack.bottom+stack.size-15]
			stack.size++
			stack.inner.top++
			pc++
			continue mainLoop

		case DUP16:
			if sLen := stack.len(); sLen < 16 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 16}
			} else if sLen > 1023 {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: 1023}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size] = stack.inner.data[stack.bottom+stack.size-16]
			stack.size++
			stack.inner.top++
			pc++
			continue mainLoop

		case SWAP1:
			if sLen := stack.len(); sLen < 2 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 2}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size-2], stack.inner.data[stack.bottom+stack.size-1] = stack.inner.data[stack.bottom+stack.size-1], stack.inner.data[stack.bottom+stack.size-2]
			pc++
			continue mainLoop
		case SWAP2:
			if sLen := stack.len(); sLen < 3 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 3}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size-3], stack.inner.data[stack.bottom+stack.size-1] = stack.inner.data[stack.bottom+stack.size-1], stack.inner.data[stack.bottom+stack.size-3]
			pc++
			continue mainLoop
		case SWAP3:
			if sLen := stack.len(); sLen < 4 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 4}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size-4], stack.inner.data[stack.bottom+stack.size-1] = stack.inner.data[stack.bottom+stack.size-1], stack.inner.data[stack.bottom+stack.size-4]
			pc++
			continue mainLoop
		case SWAP4:
			if sLen := stack.len(); sLen < 5 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 5}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size-5], stack.inner.data[stack.bottom+stack.size-1] = stack.inner.data[stack.bottom+stack.size-1], stack.inner.data[stack.bottom+stack.size-5]
			pc++
			continue mainLoop
		case SWAP5:
			if sLen := stack.len(); sLen < 6 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 6}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size-6], stack.inner.data[stack.bottom+stack.size-1] = stack.inner.data[stack.bottom+stack.size-1], stack.inner.data[stack.bottom+stack.size-6]
			pc++
			continue mainLoop
		case SWAP6:
			if sLen := stack.len(); sLen < 7 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 7}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size-7], stack.inner.data[stack.bottom+stack.size-1] = stack.inner.data[stack.bottom+stack.size-1], stack.inner.data[stack.bottom+stack.size-7]
			pc++
			continue mainLoop
		case SWAP7:
			if sLen := stack.len(); sLen < 8 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 8}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size-8], stack.inner.data[stack.bottom+stack.size-1] = stack.inner.data[stack.bottom+stack.size-1], stack.inner.data[stack.bottom+stack.size-8]
			pc++
			continue mainLoop
		case SWAP8:
			if sLen := stack.len(); sLen < 9 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 9}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size-9], stack.inner.data[stack.bottom+stack.size-1] = stack.inner.data[stack.bottom+stack.size-1], stack.inner.data[stack.bottom+stack.size-9]
			pc++
			continue mainLoop
		case SWAP9:
			if sLen := stack.len(); sLen < 10 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 10}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size-10], stack.inner.data[stack.bottom+stack.size-1] = stack.inner.data[stack.bottom+stack.size-1], stack.inner.data[stack.bottom+stack.size-10]
			pc++
			continue mainLoop
		case SWAP10:
			if sLen := stack.len(); sLen < 11 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 11}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size-11], stack.inner.data[stack.bottom+stack.size-1] = stack.inner.data[stack.bottom+stack.size-1], stack.inner.data[stack.bottom+stack.size-11]
			pc++
			continue mainLoop
		case SWAP11:
			if sLen := stack.len(); sLen < 12 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 12}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size-12], stack.inner.data[stack.bottom+stack.size-1] = stack.inner.data[stack.bottom+stack.size-1], stack.inner.data[stack.bottom+stack.size-12]
			pc++
			continue mainLoop
		case SWAP12:
			if sLen := stack.len(); sLen < 13 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 13}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size-13], stack.inner.data[stack.bottom+stack.size-1] = stack.inner.data[stack.bottom+stack.size-1], stack.inner.data[stack.bottom+stack.size-13]
			pc++
			continue mainLoop
		case SWAP13:
			if sLen := stack.len(); sLen < 14 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 14}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size-14], stack.inner.data[stack.bottom+stack.size-1] = stack.inner.data[stack.bottom+stack.size-1], stack.inner.data[stack.bottom+stack.size-14]
			pc++
			continue mainLoop
		case SWAP14:
			if sLen := stack.len(); sLen < 15 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 15}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size-15], stack.inner.data[stack.bottom+stack.size-1] = stack.inner.data[stack.bottom+stack.size-1], stack.inner.data[stack.bottom+stack.size-15]
			pc++
			continue mainLoop
		case SWAP15:
			if sLen := stack.len(); sLen < 16 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 16}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size-16], stack.inner.data[stack.bottom+stack.size-1] = stack.inner.data[stack.bottom+stack.size-1], stack.inner.data[stack.bottom+stack.size-16]
			pc++
			continue mainLoop
		case SWAP16:
			if sLen := stack.len(); sLen < 17 {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: 17}
			}
			if contract.Gas.RegularGas < 3 {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= 3
			stack.inner.data[stack.bottom+stack.size-17], stack.inner.data[stack.bottom+stack.size-1] = stack.inner.data[stack.bottom+stack.size-1], stack.inner.data[stack.bottom+stack.size-17]
			pc++
			continue mainLoop
		default:
			operation := table[op]
			if sLen := stack.len(); sLen < operation.minStack {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: operation.minStack}
			} else if sLen > operation.maxStack {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: operation.maxStack}
			}
			cost := operation.constantGas
			if contract.Gas.RegularGas < cost {
				return nil, ErrOutOfGas
			}
			contract.Gas.RegularGas -= cost
			var memorySize uint64
			if operation.dynamicGas != nil {
				if operation.memorySize != nil {
					memSize, overflow := operation.memorySize(stack)
					if overflow {
						return nil, ErrGasUintOverflow
					}
					if memorySize, overflow = math.SafeMul(toWordSize(memSize), 32); overflow {
						return nil, ErrGasUintOverflow
					}
				}
				var dynamicCost GasCosts
				dynamicCost, err = operation.dynamicGas(evm, contract, stack, mem, memorySize)
				if err != nil {
					return nil, fmt.Errorf("%w: %v", ErrOutOfGas, err)
				}
				if contract.Gas.RegularGas < dynamicCost.RegularGas {
					return nil, ErrOutOfGas
				}
				contract.Gas.RegularGas -= dynamicCost.RegularGas
			}
			if memorySize > 0 {
				mem.Resize(memorySize)
			}
			res, err = operation.execute(&pc, evm, scope)
			if err != nil {
				break mainLoop
			}
			pc++
			continue mainLoop
		}
	}
	if err == errStopToken {
		err = nil
	}
	return res, err
}
