// Copyright 2025 The go-ethereum Authors
// This file is part of the go-ethereum library.
//
// The go-ethereum library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The go-ethereum library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the go-ethereum library. If not, see <http://www.gnu.org/licenses/>.

package filtermaps

import (
	"errors"
	"sync/atomic"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
)

var (
	ErrInvalidView = errors.New("index view already invalidated")
)

// IndexView provides an immutable view of the index. It has a direct reference
// to a fixed number of finishedMaps and one memoryMap at the head end of the
// index, the rest is served from the underlying mapStorage.
// Each IndexView instance is tracked by Indexer that ensures that all data
// required to provide this view stays available in mapStorage (tailEpoch is
// not unindexed while the view is active). In the very unlikely case when
// mapStorage is reverted to an earlier point than IndexView's own finishedMaps
// (could happen in case of a big reorg or chain head reset) the view will be
// invalidated so that it returns ErrInvalidView to all read operations (it
// never returns an invalid result).
type IndexView struct {
	refCount, invalid int32
	storage           *mapStorage

	tailEpoch     uint32               //TODO apply to read functions
	blockRange    common.Range[uint64] //TODO apply to read functions
	headBlockHash common.Hash
	headLvPointer uint64 // points after head block delimiter

	firstMemoryMap   uint32
	firstMemoryBlock uint64
	finishedMaps     []*finishedMap
	headMapIndex     uint32
	headMap          *memoryMap
}

// Release decreases the reference counter of the view. Indexer will eventually
// clean it up once it is no longer in either canonicalHashes or recentHashes
// and all instances returned by GetIndexView have been released by the caller.
func (iv *IndexView) Release() {
	iv.addRefCount(-1)
}

// addRefCount increases or decreases the reference counter with the given amount
// and returns true if the view can be deleted.
func (iv *IndexView) addRefCount(add int32) bool {
	return atomic.AddInt32(&iv.refCount, add) <= 0
}

// checkReleased returns true if the view does not have a positive reference
// counter and therefore can be deleted.
func (iv *IndexView) checkReleased() bool {
	return atomic.LoadInt32(&iv.refCount) <= 0
}

// invalidate sets the invalid flag of the view. It is guaranteed that all read
// operations return ErrInvalidView after invalidate is called.
// Note that a view with no more references is deleted from Indexer and also
// invalidated but an invalidated view does not automatically get released.
func (iv *IndexView) invalidate() {
	atomic.StoreInt32(&iv.invalid, 1)
}

// checkInvalid returns true if the view has been invalidated.
func (iv *IndexView) checkInvalid() bool {
	return atomic.LoadInt32(&iv.invalid) != 0
}

// GetParams returns the general index parameters.
func (iv *IndexView) GetParams() *Params {
	return iv.storage.params
}

// BlockRange returns the block range in which the index data is available.
func (iv *IndexView) BlockRange() common.Range[uint64] {
	return iv.blockRange
}

// getBlockLvPointer returns the starting log value index where the log values
// generated by the given block are located.
// Note that the function returns a valid result (the next free log value index)
// for BlockRange().AfterLast().
func (iv *IndexView) GetBlockLvPointer(blockNumber uint64) (uint64, error) {
	if iv.checkInvalid() {
		return 0, ErrInvalidView
	}

	if blockNumber < iv.firstMemoryBlock {
		lvPtr, err := iv.storage.getBlockLvPointer(blockNumber)
		if iv.checkInvalid() {
			return 0, ErrInvalidView
		}
		return lvPtr, err
	}
	if blockNumber == iv.blockRange.AfterLast() {
		return iv.headLvPointer, nil
	}
	if blockNumber > iv.blockRange.AfterLast() {
		return 0, errors.New("block number out of range")
	}
	for _, fm := range iv.finishedMaps {
		if blockNumber >= fm.firstBlock() && blockNumber <= fm.lastBlock.number {
			return fm.blockPtrs[blockNumber-fm.firstBlock()], nil
		}
	}
	if blockNumber >= iv.headMap.firstBlock() && blockNumber <= iv.headMap.lastBlock.number {
		return iv.headMap.blockPtrs[blockNumber-iv.headMap.firstBlock()], nil
	}
	panic("IndexView.GetBlockLvPointer: gap in blockLvPtrs")
}

// GetLastBlockOfMap returns the number and hash of the block that generated the
// last log value entry of the given map.
func (iv *IndexView) GetLastBlockOfMap(mapIndex uint32) (uint64, common.Hash, error) {
	if iv.checkInvalid() {
		return 0, common.Hash{}, ErrInvalidView
	}

	if mapIndex < iv.firstMemoryMap {
		lastNumber, lastHash, err := iv.storage.getLastBlockOfMap(mapIndex)
		if iv.checkInvalid() {
			return 0, common.Hash{}, ErrInvalidView
		}
		return lastNumber, lastHash, err
	}
	if mapIndex > iv.headMapIndex {
		return 0, common.Hash{}, errors.New("map index out of range")
	}
	if mapIndex == iv.headMapIndex {
		return iv.headMap.lastBlock.number, iv.headMap.lastBlock.hash, nil
	}
	fm := iv.finishedMaps[mapIndex-iv.firstMemoryMap]
	return fm.lastBlock.number, fm.lastBlock.hash, nil
}

// GetFilterMapRows returns a batch of filter maps rows from the same row index,
// each truncated to the length limit of the specified mapping layer.
// The function assumes that the map indices are in strictly ascending order.
func (iv *IndexView) GetFilterMapRows(mapIndices []uint32, rowIndex, layerIndex uint32) (rows []FilterRow, err error) {
	if iv.checkInvalid() {
		return nil, ErrInvalidView
	}

	dbIndices := len(mapIndices)
	for dbIndices > 0 && mapIndices[dbIndices-1] >= iv.firstMemoryMap {
		dbIndices--
	}
	if dbIndices > 0 {
		rows, err = iv.storage.getFilterMapRows(mapIndices[:dbIndices], rowIndex, layerIndex)
		if iv.checkInvalid() {
			return nil, ErrInvalidView
		}
		if err != nil {
			return nil, err
		}
	}
	for i := dbIndices; i < len(mapIndices); i++ {
		mapIndex := mapIndices[i]
		var row FilterRow
		if mapIndex == iv.headMapIndex {
			row = iv.headMap.getRow(rowIndex, iv.storage.params.getMaxRowLength(layerIndex+1))
		}
		if mapIndex < iv.headMapIndex {
			row = iv.finishedMaps[mapIndex-iv.firstMemoryMap].getRow(rowIndex, iv.storage.params.getMaxRowLength(layerIndex+1))
		}
		rows = append(rows, row)
	}
	return rows, nil
}

// renderState renders maps in a fixed map range based on externally delivered
// block data. It is initialized by indexer either at a map boundary or based
// on an IndexView snapshot.
type renderState struct {
	params           *Params
	renderRange      common.Range[uint32]
	lvPointer        uint64
	mapIndex         uint32
	currentMap       *memoryMap
	finishedMaps     []*finishedMap
	nextBlock        uint64
	partialBlock     bool
	partialBlockHash common.Hash
}

// checkNextHash returns true if the next block with the given block hash can
// be added to the index. This is only important in case of the first block
// after initializing renderState on a map boundary, in which case part of the
// first block is already rendered on the previous map and therefore adding any
// other block than this first would result in an invalid index. In this case
// it is mandatory to do this check.
func (rs *renderState) checkNextHash(hash common.Hash) bool {
	if rs.partialBlock && rs.partialBlockHash != hash {
		return false
	}
	rs.partialBlock = false
	return true
}

// addReceipts adds log values to the index based on block receipts.
func (rs *renderState) addReceipts(receipts types.Receipts) {
	if rs.partialBlock {
		panic("checkNextHash has to be called before adding partially rendered block")
	}
	if rs.currentMap != nil {
		rs.currentMap.blockPtrs = append(rs.currentMap.blockPtrs, rs.lvPointer)
		rs.currentMap.lastBlock = lastBlockOfMap{number: rs.nextBlock} // hash will be set by addHeader
	}
	for _, receipt := range receipts {
		//TODO add tx delimiter
		for _, log := range receipt.Logs {
			mapRemaining := rs.params.valuesPerMap - rs.lvPointer%rs.params.valuesPerMap
			if mapRemaining <= uint64(len(log.Topics)) {
				rs.advance(mapRemaining)
			}
			if rs.currentMap != nil {
				rs.addValue(addressValue(log.Address))
				for _, topic := range log.Topics {
					rs.addValue(topicValue(topic))
				}
			} else {
				rs.advance(uint64(len(log.Topics) + 1))
			}
			if rs.finished() {
				return
			}
		}
	}
}

// addHeader adds the block delimiter after the log values generated by the
// block (addHeader should always be called after addReceipts). If any maps have
// been completed since the last addHeader call (or initialization if it is the
// first call) then they are returned here.
func (rs *renderState) addHeader(header *types.Header) (uint32, []*finishedMap) {
	if rs.partialBlock {
		panic("checkNextHash has to be called before adding partially rendered block")
	}
	if rs.nextBlock != header.Number.Uint64() {
		panic("wrong block number")
	}
	if !rs.finished() {
		rs.advance(1) //TODO blockValue
	}
	rs.nextBlock++
	lastBlock := lastBlockOfMap{number: header.Number.Uint64(), hash: header.Hash()}
	if rs.currentMap != nil {
		rs.currentMap.lastBlock = lastBlock
	}
	for _, fm := range rs.finishedMaps {
		fm.lastBlock = lastBlock
	}
	firstMemoryMap, finishedMaps := rs.mapIndex-uint32(len(rs.finishedMaps)), rs.finishedMaps
	rs.finishedMaps = nil
	return firstMemoryMap, finishedMaps
}

// addValue adds an entry based on the given log value hash to the current
// rendered map and also advances lvPointer and mapIndex. Note that it assumes
// that currentMap is not nil. If mapIndex is outside renderRange and there is
// no rendered map then only advance should be called (also it's unnecessary to
// calculage the log value hash).
func (rs *renderState) addValue(logValue common.Hash) {
	if rs.renderRange.Includes(rs.mapIndex) {
		for layerIndex := uint32(0); ; layerIndex++ {
			rowIndex := rs.params.rowIndex(rs.mapIndex, layerIndex, logValue)
			if rs.currentMap.rowLength(rowIndex) < rs.params.getMaxRowLength(layerIndex) {
				rs.currentMap.addToRow(rowIndex, rs.params.columnIndex(rs.lvPointer, &logValue))
				break
			}
		}
	}
	rs.advance(1)
}

// advance adds the specified count to lvPointer and also advandces mapIndex and
// creates a new map if necessary. Finished maps are collected in a list until
// the next addHeader call.
func (rs *renderState) advance(count uint64) {
	rs.lvPointer += count
	if uint32(rs.lvPointer>>rs.params.logValuesPerMap) > rs.mapIndex {
		if rs.currentMap != nil {
			rs.finishedMaps = append(rs.finishedMaps, rs.currentMap.finished())
		}
		rs.mapIndex++
		if rs.renderRange.Includes(rs.mapIndex) {
			rs.currentMap = rs.params.newMemoryMap()
		} else {
			rs.currentMap = nil
		}
	}
}

// finished returns true if renderRange has been completed.
func (rs *renderState) finished() bool {
	return rs.mapIndex >= rs.renderRange.AfterLast()
}
