FROM alpine:3.15 AS base
RUN apk add --no-cache alpine-sdk cmake linux-headers boost-dev boost-static
ENV LDFLAGS="-static"
WORKDIR /build

FROM base as tests
RUN git clone --depth 1 -b zkevm https://github.com/privacy-scaling-explorations/eth-tests.git /tests

FROM base AS retesteth
RUN git clone --depth 1 -b develop https://github.com/ethereum/retesteth.git /retesteth
RUN cmake /retesteth -DCMAKE_BUILD_TYPE=Release && make && cp retesteth/retesteth /target

FROM golang:1.18-alpine as geth
RUN apk add --no-cache gcc musl-dev linux-headers git
WORKDIR /go-ethereum
COPY go.mod .
COPY go.sum .
RUN go mod download
ADD . .
RUN go run build/ci.go install ./cmd/evm 
RUN cp build/bin/evm /target

FROM alpine:3.15
ENV ETHEREUM_TEST_PATH="/tests"
COPY --from=retesteth /target /bin/retesteth
COPY --from=tests /tests /tests
COPY --from=geth /target /bin/evm
COPY docker/retesteth/data /root/.retesteth
