// Copyright 2026 The go-ethereum Authors
// This file is part of the go-ethereum library.
//
// The go-ethereum library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The go-ethereum library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the go-ethereum library. If not, see <http://www.gnu.org/licenses/>.

package types

import (
	"crypto/sha256"
	"encoding/binary"
	"math/bits"
	"sort"
	"strings"
	"testing"

	ssz "github.com/ferranbt/fastssz"

	"github.com/ethereum/go-ethereum/common"
)

// naiveTableRoot is an independent oracle for merkleizeEntries: it pads the
// leaf list with zero leaves to the full 2^ceil(log2(n)) width and folds
// naively, instead of growing the layer with zero-subtree ladder entries. The
// two constructions are equivalent because sha256(z || z) makes an explicit
// zero-leaf subtree hash to the ladder value of the same height.
func naiveTableRoot(entries []IndexEntry) common.Hash {
	n := len(entries)
	if n == 0 {
		return common.Hash{}
	}
	width := 1 << bits.Len(uint(n-1)) // 2^ceil(log2(n)); 1 for n == 1
	layer := make([][32]byte, width)
	hasher := sha256.New()
	for i, entry := range entries {
		hasher.Reset()
		hasher.Write(entry)
		hasher.Sum(layer[i][:0])
	}
	for count := width; count > 1; count /= 2 {
		for i := 0; i < count/2; i++ {
			hasher.Reset()
			hasher.Write(layer[2*i][:])
			hasher.Write(layer[2*i+1][:])
			hasher.Sum(layer[i][:0])
		}
	}
	var countEnc [32]byte
	binary.LittleEndian.PutUint64(countEnc[:8], uint64(n))
	hasher.Reset()
	hasher.Write(layer[0][:])
	hasher.Write(countEnc[:])
	var root common.Hash
	hasher.Sum(root[:0])
	return root
}

// TestMerkleizeEntriesVectors pins the table root against golden vectors.
// Entries are embedded pre-sorted and must not be re-sorted: the vectors order
// address entries by the full 32-byte value, which cannot be reproduced from
// the 20-byte address encodings IndexEntry carries.
func TestMerkleizeEntriesVectors(t *testing.T) {
	// Vector entries, pre-sorted. Generated by: value = sha256(be64(i)),
	// type = i mod 7 (0 block, 1 transaction, 2 address, 3-6 topics), address
	// entries zero the top 12 bytes of the value for even i, block =
	// 1000000 + 3*i, tx = i mod 5, log = i mod 3, ordered by (type, value,
	// block, tx, log) with values compared as full 32-byte words.
	e1 := "0000af5570f5a1810b7af78caf4bc70a660f0df51e42baf91d4de5b2328de0e83dfc00000000000f4240"
	e2 := "0001cd2662154e6d76b2b2b92e70c0cac3ccf534f9b74eb5b89819ec509083d00a5000000000000f42430000000100000001"
	e3 := "0002371f1f04ff6d2470f24aa9bd886540e5dce77f7000000000000f42460000000200000002"
	e4 := "0003d5688a52d55a02ec4aea5ec1eadfffe1c9e0ee6a4ddbe2377f98326d42dfc97500000000000f42490000000300000000"
	e5 := "00048005f02d43fa06e7d0585fb64c961d57e318b27a145c857bcd3a6bdb413ff7fc00000000000f424c0000000400000001"
	e6 := "0000a3eb8db89fc5123ccfd49585059f292bc40a1c0d550b860f24f84efb4760fbf200000000000f4255"
	e7 := "00055dee4dd60ff8d0ba9900fe91e90e0dcf65f0570d42c431f727d0300dd70dc43100000000000f424f0000000000000002"
	e8 := "000614ac577cdb2ef6d986078b4054cc9893a9a14a16dbb0d8f37b89167c1f1aacdf00000000000f42520000000100000000"
	a := "000076b1ff1a6cb1b23738647eb1ea40d8f14b037285e457214aab335874feb6e79e00000000000f426a"
	b := "00014c0e071832d527694adea57b50dd7b2164c2a47c02940dcf26fa07c44d6d222a00000000000f42580000000300000002"
	c := "0001e66c57014a6156061ae669809ec5d735e484e8fcfd540e110c9b04f84c0b450400000000000f426d0000000000000000"
	// Positions 8 and 9 below are Compare-ordered (by the full 32-byte value),
	// not encoding-ordered; keep them exactly as the vector lists them.
	d := "0002c40fe98ca6d2d5a29755bc5a04824c36082a61d100000000000f42700000000100000001"
	f := "00020610304aca7d4acf1f2de5ce6812a8c43610c6e600000000000f425b0000000400000000"
	g := "00038d85f8467240628a94819b26bee26e3a9b2804334c63482deacec8d64ab4e1e700000000000f425e0000000000000001"
	h := "00040b5000b73a53f0916c93c68f4b9b6ba8af5a10978634ae4f2237e1f3fbe324fa00000000000f42610000000100000002"
	i := "0005d27a8d9a8d38c7a37c922450a7a1961f138abfa25f5da3df2b972820715fa5ae00000000000f42640000000200000000"
	j := "00061f5edc6f1efb165d45a654798d4baaa50e3b4d24182913aef5110a15580ebaad00000000000f42670000000300000001"

	tests := []struct {
		n       int
		root    string
		entries []string
	}{
		{1, "0x575b05a31d5f1f0ebf8c22159411a269021378700b487d729f83863c2ca8f45f", []string{e1}},
		{2, "0x824cb8c3b998a698e48c81b628c8d5cfc84274403fcd1ad73f09c83c722d8bf2", []string{e1, e2}},
		{3, "0x0da4f88e3d91f9090f69f937f346794c620e5a84edb6d53d6383d83078b17a14", []string{e1, e2, e3}},
		{5, "0xfcb2fc71b718d04aa84a558b3e5d19adf84cb462ef4cdf0d76ec4b30779808e8", []string{e1, e2, e3, e4, e5}},
		{8, "0xd421134ba5bcd1f1e446362bdde82a13b7d05e2c57688ba778bee2c5e5b121b0", []string{e6, e1, e2, e3, e4, e5, e7, e8}},
		{17, "0x28cd1d67f99cd6b151c1e9daa9cc82395116206393f48f0b39a8906350577a97", []string{a, e6, e1, b, e2, c, e3, d, f, g, e4, h, e5, e7, i, e8, j}},
		// A single 42-byte block entry: pins that the count is mixed in even
		// at depth 0, where the tree root is the leaf itself.
		{1, "0xb9ce2007a76623771529c0868ce41b2e0d26efdb29db211b801d456c8743baf2",
			[]string{"0000" + strings.Repeat("10", 32) + "00000000000003e8"}},
	}
	for _, tt := range tests {
		entries := make([]IndexEntry, len(tt.entries))
		for k, entry := range tt.entries {
			entries[k] = common.FromHex(entry)
		}
		want := common.HexToHash(tt.root)
		if got := merkleizeEntries(entries); got != want {
			t.Errorf("n=%d: merkleizeEntries root %x, want %s", tt.n, got, tt.root)
		}
		if got := naiveTableRoot(entries); got != want {
			t.Errorf("n=%d: naive oracle root %x, want %s", tt.n, got, tt.root)
		}
	}
}

// TestMerkleizeEntriesEdges covers the empty and single-entry tables: an
// empty table has no entries to hash and no root (the zero hash), and a
// single-entry table mixes the count into the leaf itself.
func TestMerkleizeEntriesEdges(t *testing.T) {
	if root := merkleizeEntries(nil); root != (common.Hash{}) {
		t.Errorf("empty table root = %x, want the zero hash", root)
	}
	if root := naiveTableRoot(nil); root != (common.Hash{}) {
		t.Errorf("naive oracle empty table root = %x, want the zero hash", root)
	}
}

// syntheticEntries regenerates the golden vector scheme with canonical
// addresses (IndexEntry carries the low 20 bytes of the value, equivalent to
// a zeroed top), so the vector ordering and the encoding ordering coincide.
func syntheticEntries(n int) []IndexEntry {
	entries := make([]IndexEntry, n)
	for i := 0; i < n; i++ {
		value := sha256.Sum256(binary.BigEndian.AppendUint64(nil, uint64(i)))
		typ := EntryType(i % 7)
		content := value[:]
		if typ == EntryTypeLogAddress {
			content = value[12:]
		}
		entries[i] = EncodeEntry(typ, content, 1000000+3*uint64(i), uint32(i%5), uint32(i%3))
	}
	sort.Slice(entries, func(i, j int) bool {
		return CompareEntries(entries[i], entries[j]) < 0
	})
	return entries
}

// TestMerkleizeEntriesDifferential cross-checks the hand-rolled tree against
// fastssz's MerkleizeWithMixin over the same leaf sequence, and against the
// naive oracle, for sizes spanning even/odd, powers of two and padded shapes.
func TestMerkleizeEntriesDifferential(t *testing.T) {
	for _, n := range []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 15, 16, 17, 31, 32, 33, 63, 64, 100, 255, 256, 257, 1000} {
		entries := syntheticEntries(n)
		hh := ssz.NewHasher()
		for _, entry := range entries {
			leaf := sha256.Sum256(entry)
			hh.Append(leaf[:])
		}
		hh.MerkleizeWithMixin(0, uint64(n), uint64(n))
		root, err := hh.HashRoot()
		if err != nil {
			t.Fatalf("n=%d: fastssz HashRoot error: %v", n, err)
		}
		if got := merkleizeEntries(entries); (common.Hash)(root) != got {
			t.Errorf("n=%d: merkleizeEntries root %x, fastssz root %x", n, got, root)
		}
		if got := naiveTableRoot(entries); got != merkleizeEntries(entries) {
			t.Errorf("n=%d: naive oracle root %x differs from merkleizeEntries", n, got)
		}
	}
}
