// Copyright 2024 The go-ethereum Authors
// This file is part of the go-ethereum library.
//
// The go-ethereum library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The go-ethereum library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the go-ethereum library. If not, see <http://www.gnu.org/licenses/>.

package types

import (
	"bytes"
	"encoding/hex"
	"strings"
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/rlp"
	"github.com/holiman/uint256"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// pyquarkchain test vectors generated by:
//
//	from quarkchain.evm.state import _Account, TokenBalancePair
//	import rlp
//	from rlp.sedes import BigEndianInt, binary, CountableList, big_endian_int
//
// See pyquarkchain/quarkchain/evm/state.py _Account for the canonical format.
//
// All vectors use:
//   - storage  = EmptyRootHash (keccak256 of empty)
//   - code_hash = EmptyCodeHash (keccak256 of empty string)
//   - full_shard_key = 1  (BigEndianInt(4) → always 4 bytes on the wire)
//   - optional = b""
var (
	pyqkcVecNonce1QKC1000        = mustHex("f853018900c7c6828bb08203e8a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a0c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470840000000180")
	pyqkcVecNonce5QKC2000MNT500  = mustHex("f858058e00ccc4648201f4c6828bb08207d0a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a0c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470840000000180")
	pyqkcVecZeroAccount          = mustHex("f84a8080a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a0c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470840000000180")
)

func mustHex(s string) []byte {
	b, err := hex.DecodeString(s)
	if err != nil {
		panic(err)
	}
	return b
}

// TestStateAccountEncodeDecodeRoundtrip verifies that EncodeRLP→DecodeRLP is
// a lossless roundtrip for all fields including FullShardKey.
func TestStateAccountEncodeDecodeRoundtrip(t *testing.T) {
	cases := []struct {
		name string
		acct StateAccount
	}{
		{
			name: "empty",
			acct: *NewEmptyStateAccount(),
		},
		{
			name: "nonce1 QKC=1000 shard=1",
			acct: StateAccount{
				Nonce:        1,
				Balance:      uint256.NewInt(1000),
				Root:         EmptyRootHash,
				CodeHash:     EmptyCodeHash[:],
				FullShardKey: 1,
			},
		},
		{
			name: "nonce5 QKC=2000 MNT[100]=500 shard=0x2f3e",
			acct: StateAccount{
				Nonce:    5,
				Balance:  uint256.NewInt(2000),
				Root:     EmptyRootHash,
				CodeHash: EmptyCodeHash[:],
				MntBalances: NewTokenBalancesWithMap(map[uint64]*uint256.Int{
					100: uint256.NewInt(500),
				}),
				FullShardKey: 0x2f3e,
			},
		},
		{
			name: "non-empty root and codehash shard=0x72ea",
			acct: StateAccount{
				Nonce:        3,
				Balance:      uint256.NewInt(1e18),
				Root:         common.HexToHash("0xdeadbeef"),
				CodeHash:     common.Hex2Bytes("abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890"),
				FullShardKey: 0x72ea,
			},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			encoded, err := rlp.EncodeToBytes(&tc.acct)
			require.NoError(t, err)

			var decoded StateAccount
			require.NoError(t, rlp.DecodeBytes(encoded, &decoded))

			assert.Equal(t, tc.acct.Nonce, decoded.Nonce)
			assert.Equal(t, tc.acct.Root, decoded.Root)
			assert.Equal(t, tc.acct.CodeHash, decoded.CodeHash)
			assert.Equal(t, tc.acct.FullShardKey, decoded.FullShardKey)
			require.NotNil(t, decoded.Balance)
			assert.Equal(t, tc.acct.Balance, decoded.Balance)
			if tc.acct.MntBalances == nil || tc.acct.MntBalances.IsBlank() {
				assert.True(t, decoded.MntBalances == nil || decoded.MntBalances.IsBlank())
			} else {
				require.NotNil(t, decoded.MntBalances)
				assert.Equal(t, tc.acct.MntBalances.GetBalanceMap(), decoded.MntBalances.GetBalanceMap())
			}
		})
	}
}

// TestStateAccountPyquarkchainDecodeCompatibility verifies that goshard can
// decode blobs produced by pyquarkchain. These are the authoritative wire
// vectors for the QKC 6-element RLP format. All vectors use full_shard_key=1.
func TestStateAccountPyquarkchainDecodeCompatibility(t *testing.T) {
	cases := []struct {
		name             string
		blob             []byte
		wantNonce        uint64
		wantQKC          *uint256.Int
		wantMNT          map[uint64]*uint256.Int // nil = no MNT tokens expected
		wantFullShardKey uint32
	}{
		{
			name:             "nonce=1 QKC=1000",
			blob:             pyqkcVecNonce1QKC1000,
			wantNonce:        1,
			wantQKC:          uint256.NewInt(1000),
			wantFullShardKey: 1,
		},
		{
			name:             "nonce=5 QKC=2000 MNT[100]=500",
			blob:             pyqkcVecNonce5QKC2000MNT500,
			wantNonce:        5,
			wantQKC:          uint256.NewInt(2000),
			wantMNT:          map[uint64]*uint256.Int{100: uint256.NewInt(500)},
			wantFullShardKey: 1,
		},
		{
			name:             "zero account",
			blob:             pyqkcVecZeroAccount,
			wantNonce:        0,
			wantQKC:          uint256.NewInt(0),
			wantFullShardKey: 1,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			var acct StateAccount
			require.NoError(t, rlp.DecodeBytes(tc.blob, &acct))

			assert.Equal(t, tc.wantNonce, acct.Nonce)
			assert.Equal(t, EmptyRootHash, acct.Root)
			assert.Equal(t, EmptyCodeHash[:], acct.CodeHash)
			assert.Equal(t, tc.wantFullShardKey, acct.FullShardKey)
			require.NotNil(t, acct.Balance)
			assert.Equal(t, tc.wantQKC, acct.Balance)

			if tc.wantMNT == nil {
				assert.True(t, acct.MntBalances == nil || acct.MntBalances.IsBlank())
			} else {
				require.NotNil(t, acct.MntBalances)
				assert.Equal(t, tc.wantMNT, acct.MntBalances.GetBalanceMap())
			}
		})
	}
}

// TestStateAccountPyquarkchainEncodeCompatibility verifies that goshard
// produces byte-for-byte identical output to pyquarkchain for the same account.
// This is the strongest compatibility check: same input → same wire bytes.
func TestStateAccountPyquarkchainEncodeCompatibility(t *testing.T) {
	cases := []struct {
		name string
		acct StateAccount
		want []byte
	}{
		{
			name: "nonce=1 QKC=1000",
			acct: StateAccount{
				Nonce:        1,
				Balance:      uint256.NewInt(1000),
				Root:         EmptyRootHash,
				CodeHash:     EmptyCodeHash[:],
				FullShardKey: 1,
			},
			want: pyqkcVecNonce1QKC1000,
		},
		{
			name: "nonce=5 QKC=2000 MNT[100]=500",
			acct: StateAccount{
				Nonce:    5,
				Balance:  uint256.NewInt(2000),
				Root:     EmptyRootHash,
				CodeHash: EmptyCodeHash[:],
				MntBalances: NewTokenBalancesWithMap(map[uint64]*uint256.Int{
					100: uint256.NewInt(500),
				}),
				FullShardKey: 1,
			},
			want: pyqkcVecNonce5QKC2000MNT500,
		},
		{
			name: "zero account",
			acct: StateAccount{
				Nonce:        0,
				Balance:      uint256.NewInt(0),
				Root:         EmptyRootHash,
				CodeHash:     EmptyCodeHash[:],
				FullShardKey: 1,
			},
			want: pyqkcVecZeroAccount,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, err := rlp.EncodeToBytes(&tc.acct)
			require.NoError(t, err)
			assert.Equal(t, hex.EncodeToString(tc.want), hex.EncodeToString(got),
				"goshard encoding must match pyquarkchain byte-for-byte")
		})
	}
}

// TestSlimRLPRoundTripEquivalence verifies that for non-MNT accounts (no MntBalances),
// the round-trip slim-RLP → decode → QKC-encode produces the same bytes as direct
// QKC-encode. This is the invariant that allows execute.go to use slim-RLP as the
// accountOrigin format for history reversal without affecting trie root correctness.
//
// Note: SlimAccount does not carry FullShardKey. Both paths therefore encode with
// FullShardKey=0, so the test holds — but the slim-RLP path should only be used
// for accounts where FullShardKey is known to be zero (e.g. freshly created accounts
// before any shard key is set).
func TestSlimRLPRoundTripEquivalence(t *testing.T) {
	cases := []struct {
		name string
		acc  StateAccount
	}{
		{"zero balance, empty root", StateAccount{Nonce: 0, Balance: new(uint256.Int), Root: EmptyRootHash, CodeHash: EmptyCodeHash.Bytes()}},
		{"nonzero balance, empty root", StateAccount{Nonce: 5, Balance: uint256.NewInt(1_000_000), Root: EmptyRootHash, CodeHash: EmptyCodeHash.Bytes()}},
		{"with storage root", StateAccount{Nonce: 1, Balance: uint256.NewInt(42), Root: common.HexToHash("0xabcdef"), CodeHash: EmptyCodeHash.Bytes()}},
		{"with code hash", StateAccount{Nonce: 99, Balance: uint256.NewInt(999), Root: EmptyRootHash, CodeHash: common.FromHex("0xdeadbeef" + strings.Repeat("00", 28))}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			// Path A: direct QKC encode
			directQKC, err := rlp.EncodeToBytes(&tc.acc)
			if err != nil {
				t.Fatalf("direct QKC encode: %v", err)
			}
			// Path B: slim-RLP → FullAccount decode → QKC encode (execute.go path)
			slim := SlimAccountRLP(tc.acc)
			decoded, err := FullAccount(slim)
			if err != nil {
				t.Fatalf("FullAccount decode: %v", err)
			}
			viaSlim, err := rlp.EncodeToBytes(decoded)
			if err != nil {
				t.Fatalf("QKC encode after slim round-trip: %v", err)
			}
			if !bytes.Equal(directQKC, viaSlim) {
				t.Errorf("mismatch:\n  direct QKC: %x\n  via slim:   %x", directQKC, viaSlim)
			}
		})
	}
}
