CREATE TABLE IF NOT EXISTS blocks (
  hash text primary key,
  coinbase text, 
  number bigint
);

CREATE TABLE IF NOT EXISTS txs (
  txHash text,
  to_addr text,
  from_addr text,
  blockhash text references blocks(hash),
  amount numeric,
  gasprice numeric,
  gas numeric,
  nonce numeric,
  data bytea
);

CREATE TABLE IF NOT EXISTS accounts (
  addr text primary key unique,
  balance numeric
);