#!/bin/bash
# This is a postinstallation script so the service can be configured and started when requested
#
sudo adduser --disabled-password --disabled-login --shell /usr/sbin/nologin --quiet --system --no-create-home --home /nonexistent bor
sudo mkdir -p /var/lib/bor
sudo chown -R bor /var/lib/bor
sudo systemctl daemon-reload
