---
mevcommitsettlement:
  chainId: 17864
  domainId: 17864
  name: mevcommitsettlement 
  protocol: ethereum 
  rpcUrls: 
    # This RPC URL is specific to a local geth POA setup
    - http: http://172.29.0.98:8545
      pagination:
        maxBlockRange: 1000 
        maxBlockAge: 1000 
        minBlockNumber: 1000 
      retry:
        maxRequests: 5 
        baseRetryMs: 1000 
  isTestnet: true 
  # blockExplorers: # Array: List of BlockExplorer configs
  #   # Required fields:
  #   - name: My Chain Explorer # String: Human-readable name for the explorer
  #     url: https://mychain.com/explorer # String: Base URL for the explorer
  #     apiUrl: https://mychain.com/api # String: Base URL for the explorer API
  #     # Optional fields:
  #     apiKey: myapikey # String: API key for the explorer (optional)
  #     family: etherscan # ExplorerFamily: See ExplorerFamily for valid values
  nativeToken:
    name: cETH # String
    symbol: cETH # String
    decimals: 18 # Number
  displayName: MEV Commit Settlement 
  displayNameShort: MEV Commit Settlement
  logoURI: https://mychain.com/logo.png 
  blocks:
    confirmations: 12 # Number: Blocks to wait before considering a transaction confirmed
    reorgPeriod: 100 # Number: Blocks before a transaction has a near-zero chance of reverting
    estimateBlockTime: 1 

# Partial override sepolia config for custom rpc
sepolia:
  rpcUrls:
    - http: https://eth-sepolia.g.alchemy.com/v2/a0wg_g1X-Wz4IeVA-0SS3PsQhbyQNjc_
