import {
  ALL_ANDROID_GETH_RELEASES_URL,
  ALL_IOS_GETH_RELEASES_URL,
  ALL_LINUX_ALLTOOLS_GETH_RELEASES_URL,
  ALL_LINUX_GETH_RELEASES_URL,
  ALL_MACOS_ALLTOOLS_GETH_RELEASES_URL,
  ALL_MACOS_GETH_RELEASES_URL,
  ALL_WINDOWS_ALLTOOLS_GETH_RELEASES_URL,
  ALL_WINDOWS_GETH_RELEASES_URL
} from '../constants';

export const fetchXMLData = () => {
  const urls = [
    ALL_LINUX_GETH_RELEASES_URL,
    ALL_LINUX_ALLTOOLS_GETH_RELEASES_URL,
    ALL_MACOS_GETH_RELEASES_URL,
    ALL_MACOS_ALLTOOLS_GETH_RELEASES_URL,
    ALL_WINDOWS_GETH_RELEASES_URL,
    ALL_WINDOWS_ALLTOOLS_GETH_RELEASES_URL,
    ALL_ANDROID_GETH_RELEASES_URL,
    ALL_IOS_GETH_RELEASES_URL
  ];

  return Promise.all(urls.map(url => fetch(url).then(response => response.text())));
};
