{
 "title": "LDBStore and LDBDatabase",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "myinterval", "label": "resolution", "query": "5s,10s,30s,100s" },
   {
    "name": "host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "LocalStore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "LocalStore get cachehit",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$myinterval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "swarm.localstore.get.cachehit.count",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "LocalStore get cachemiss",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$myinterval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "swarm.localstore.get.cachemiss.count",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Total LocalStore.GetOrCreateRequest",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$myinterval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "swarm.localstore.getorcreaterequest.count",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "LocalStore GetOrCreateRequest ErrFetching",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$myinterval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "swarm.localstore.getorcreaterequest.errfetching.count",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "LocalStore.GetOrCreateRequest hit",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$myinterval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "swarm.localstore.getorcreaterequest.hit.count",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "LocalStore GetOrCreateRequest miss",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$myinterval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "swarm.localstore.getorcreaterequest.miss.count",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "LocalStore get error",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$myinterval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "swarm.localstore.get.error.count",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "LocalStore get ErrFetching",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$myinterval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "swarm.localstore.get.errfetching.count",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "LDBStore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "LDBStore get",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.ldbstore.get.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "LDBStore put",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.ldbstore.put.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "LDBStore SyncIterator",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.ldbstore.synciterator.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "LDBStore SyncIterator Seek/Next",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.ldbstore.synciterator.seek.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "LDBStore Collect Garbage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.ldbstore.collectgarbage.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "LDBStore Collect Garbage - Actual Deletes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.ldbstore.collectgarbage.delete.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "LDBDatabase",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "LDBDatabase get",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$myinterval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "swarm.ldbdatabase.get.count",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "LDBDatabase write",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$myinterval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "swarm.ldbdatabase.write.count",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "LDBDatabase NewIterator",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$myinterval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "swarm.ldbdatabase.newiterator.count",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}