// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/grpc/trader.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimulateBundleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  [][]byte               `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	MinTimestamp  *uint64                `protobuf:"varint,2,opt,name=min_timestamp,json=minTimestamp,proto3,oneof" json:"min_timestamp,omitempty"`
	MaxTimestamp  *uint64                `protobuf:"varint,3,opt,name=max_timestamp,json=maxTimestamp,proto3,oneof" json:"max_timestamp,omitempty"`
	RevertingTxs  []int32                `protobuf:"varint,4,rep,packed,name=reverting_txs,json=revertingTxs,proto3" json:"reverting_txs,omitempty"`
	TargetBlock   *uint64                `protobuf:"varint,5,opt,name=target_block,json=targetBlock,proto3,oneof" json:"target_block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulateBundleRequest) Reset() {
	*x = SimulateBundleRequest{}
	mi := &file_api_grpc_trader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateBundleRequest) ProtoMessage() {}

func (x *SimulateBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_trader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateBundleRequest.ProtoReflect.Descriptor instead.
func (*SimulateBundleRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_trader_proto_rawDescGZIP(), []int{0}
}

func (x *SimulateBundleRequest) GetTransactions() [][]byte {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *SimulateBundleRequest) GetMinTimestamp() uint64 {
	if x != nil && x.MinTimestamp != nil {
		return *x.MinTimestamp
	}
	return 0
}

func (x *SimulateBundleRequest) GetMaxTimestamp() uint64 {
	if x != nil && x.MaxTimestamp != nil {
		return *x.MaxTimestamp
	}
	return 0
}

func (x *SimulateBundleRequest) GetRevertingTxs() []int32 {
	if x != nil {
		return x.RevertingTxs
	}
	return nil
}

func (x *SimulateBundleRequest) GetTargetBlock() uint64 {
	if x != nil && x.TargetBlock != nil {
		return *x.TargetBlock
	}
	return 0
}

type SimulateBundleResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	GasUsed         uint64                 `protobuf:"varint,2,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Profit          []byte                 `protobuf:"bytes,3,opt,name=profit,proto3" json:"profit,omitempty"`
	CoinbaseBalance []byte                 `protobuf:"bytes,4,opt,name=coinbase_balance,json=coinbaseBalance,proto3" json:"coinbase_balance,omitempty"`
	FailedTxIndex   int32                  `protobuf:"varint,5,opt,name=failed_tx_index,json=failedTxIndex,proto3" json:"failed_tx_index,omitempty"`
	FailedTxError   string                 `protobuf:"bytes,6,opt,name=failed_tx_error,json=failedTxError,proto3" json:"failed_tx_error,omitempty"`
	TxResults       []*TxSimulationResult  `protobuf:"bytes,7,rep,name=tx_results,json=txResults,proto3" json:"tx_results,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SimulateBundleResponse) Reset() {
	*x = SimulateBundleResponse{}
	mi := &file_api_grpc_trader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateBundleResponse) ProtoMessage() {}

func (x *SimulateBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_trader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateBundleResponse.ProtoReflect.Descriptor instead.
func (*SimulateBundleResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_trader_proto_rawDescGZIP(), []int{1}
}

func (x *SimulateBundleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SimulateBundleResponse) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *SimulateBundleResponse) GetProfit() []byte {
	if x != nil {
		return x.Profit
	}
	return nil
}

func (x *SimulateBundleResponse) GetCoinbaseBalance() []byte {
	if x != nil {
		return x.CoinbaseBalance
	}
	return nil
}

func (x *SimulateBundleResponse) GetFailedTxIndex() int32 {
	if x != nil {
		return x.FailedTxIndex
	}
	return 0
}

func (x *SimulateBundleResponse) GetFailedTxError() string {
	if x != nil {
		return x.FailedTxError
	}
	return ""
}

func (x *SimulateBundleResponse) GetTxResults() []*TxSimulationResult {
	if x != nil {
		return x.TxResults
	}
	return nil
}

type TxSimulationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	GasUsed       uint64                 `protobuf:"varint,2,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	ReturnValue   []byte                 `protobuf:"bytes,4,opt,name=return_value,json=returnValue,proto3" json:"return_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxSimulationResult) Reset() {
	*x = TxSimulationResult{}
	mi := &file_api_grpc_trader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxSimulationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxSimulationResult) ProtoMessage() {}

func (x *TxSimulationResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_trader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxSimulationResult.ProtoReflect.Descriptor instead.
func (*TxSimulationResult) Descriptor() ([]byte, []int) {
	return file_api_grpc_trader_proto_rawDescGZIP(), []int{2}
}

func (x *TxSimulationResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TxSimulationResult) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *TxSimulationResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TxSimulationResult) GetReturnValue() []byte {
	if x != nil {
		return x.ReturnValue
	}
	return nil
}

type SubmitBundleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  [][]byte               `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	MinTimestamp  *uint64                `protobuf:"varint,2,opt,name=min_timestamp,json=minTimestamp,proto3,oneof" json:"min_timestamp,omitempty"`
	MaxTimestamp  *uint64                `protobuf:"varint,3,opt,name=max_timestamp,json=maxTimestamp,proto3,oneof" json:"max_timestamp,omitempty"`
	RevertingTxs  []int32                `protobuf:"varint,4,rep,packed,name=reverting_txs,json=revertingTxs,proto3" json:"reverting_txs,omitempty"`
	TargetBlock   *uint64                `protobuf:"varint,5,opt,name=target_block,json=targetBlock,proto3,oneof" json:"target_block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitBundleRequest) Reset() {
	*x = SubmitBundleRequest{}
	mi := &file_api_grpc_trader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitBundleRequest) ProtoMessage() {}

func (x *SubmitBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_trader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitBundleRequest.ProtoReflect.Descriptor instead.
func (*SubmitBundleRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_trader_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitBundleRequest) GetTransactions() [][]byte {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *SubmitBundleRequest) GetMinTimestamp() uint64 {
	if x != nil && x.MinTimestamp != nil {
		return *x.MinTimestamp
	}
	return 0
}

func (x *SubmitBundleRequest) GetMaxTimestamp() uint64 {
	if x != nil && x.MaxTimestamp != nil {
		return *x.MaxTimestamp
	}
	return 0
}

func (x *SubmitBundleRequest) GetRevertingTxs() []int32 {
	if x != nil {
		return x.RevertingTxs
	}
	return nil
}

func (x *SubmitBundleRequest) GetTargetBlock() uint64 {
	if x != nil && x.TargetBlock != nil {
		return *x.TargetBlock
	}
	return 0
}

type SubmitBundleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BundleHash    []byte                 `protobuf:"bytes,1,opt,name=bundle_hash,json=bundleHash,proto3" json:"bundle_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitBundleResponse) Reset() {
	*x = SubmitBundleResponse{}
	mi := &file_api_grpc_trader_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitBundleResponse) ProtoMessage() {}

func (x *SubmitBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_trader_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitBundleResponse.ProtoReflect.Descriptor instead.
func (*SubmitBundleResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_trader_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitBundleResponse) GetBundleHash() []byte {
	if x != nil {
		return x.BundleHash
	}
	return nil
}

type GetStorageBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contract      []byte                 `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Slots         [][]byte               `protobuf:"bytes,2,rep,name=slots,proto3" json:"slots,omitempty"`
	BlockNumber   *uint64                `protobuf:"varint,3,opt,name=block_number,json=blockNumber,proto3,oneof" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorageBatchRequest) Reset() {
	*x = GetStorageBatchRequest{}
	mi := &file_api_grpc_trader_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorageBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageBatchRequest) ProtoMessage() {}

func (x *GetStorageBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_trader_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageBatchRequest.ProtoReflect.Descriptor instead.
func (*GetStorageBatchRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_trader_proto_rawDescGZIP(), []int{5}
}

func (x *GetStorageBatchRequest) GetContract() []byte {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *GetStorageBatchRequest) GetSlots() [][]byte {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *GetStorageBatchRequest) GetBlockNumber() uint64 {
	if x != nil && x.BlockNumber != nil {
		return *x.BlockNumber
	}
	return 0
}

type GetStorageBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        [][]byte               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorageBatchResponse) Reset() {
	*x = GetStorageBatchResponse{}
	mi := &file_api_grpc_trader_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorageBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageBatchResponse) ProtoMessage() {}

func (x *GetStorageBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_trader_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageBatchResponse.ProtoReflect.Descriptor instead.
func (*GetStorageBatchResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_trader_proto_rawDescGZIP(), []int{6}
}

func (x *GetStorageBatchResponse) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type GetPendingTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinGasPrice   *uint64                `protobuf:"varint,1,opt,name=min_gas_price,json=minGasPrice,proto3,oneof" json:"min_gas_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingTransactionsRequest) Reset() {
	*x = GetPendingTransactionsRequest{}
	mi := &file_api_grpc_trader_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingTransactionsRequest) ProtoMessage() {}

func (x *GetPendingTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_trader_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetPendingTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_trader_proto_rawDescGZIP(), []int{7}
}

func (x *GetPendingTransactionsRequest) GetMinGasPrice() uint64 {
	if x != nil && x.MinGasPrice != nil {
		return *x.MinGasPrice
	}
	return 0
}

type GetPendingTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  [][]byte               `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingTransactionsResponse) Reset() {
	*x = GetPendingTransactionsResponse{}
	mi := &file_api_grpc_trader_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingTransactionsResponse) ProtoMessage() {}

func (x *GetPendingTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_trader_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetPendingTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_trader_proto_rawDescGZIP(), []int{8}
}

func (x *GetPendingTransactionsResponse) GetTransactions() [][]byte {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type CallContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          []byte                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            []byte                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Gas           *uint64                `protobuf:"varint,4,opt,name=gas,proto3,oneof" json:"gas,omitempty"`
	GasPrice      *uint64                `protobuf:"varint,5,opt,name=gas_price,json=gasPrice,proto3,oneof" json:"gas_price,omitempty"`
	Value         []byte                 `protobuf:"bytes,6,opt,name=value,proto3,oneof" json:"value,omitempty"`
	BlockNumber   *uint64                `protobuf:"varint,7,opt,name=block_number,json=blockNumber,proto3,oneof" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallContractRequest) Reset() {
	*x = CallContractRequest{}
	mi := &file_api_grpc_trader_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallContractRequest) ProtoMessage() {}

func (x *CallContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_trader_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallContractRequest.ProtoReflect.Descriptor instead.
func (*CallContractRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_trader_proto_rawDescGZIP(), []int{9}
}

func (x *CallContractRequest) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *CallContractRequest) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *CallContractRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CallContractRequest) GetGas() uint64 {
	if x != nil && x.Gas != nil {
		return *x.Gas
	}
	return 0
}

func (x *CallContractRequest) GetGasPrice() uint64 {
	if x != nil && x.GasPrice != nil {
		return *x.GasPrice
	}
	return 0
}

func (x *CallContractRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CallContractRequest) GetBlockNumber() uint64 {
	if x != nil && x.BlockNumber != nil {
		return *x.BlockNumber
	}
	return 0
}

type CallContractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReturnData    []byte                 `protobuf:"bytes,1,opt,name=return_data,json=returnData,proto3" json:"return_data,omitempty"`
	GasUsed       uint64                 `protobuf:"varint,2,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallContractResponse) Reset() {
	*x = CallContractResponse{}
	mi := &file_api_grpc_trader_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallContractResponse) ProtoMessage() {}

func (x *CallContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_trader_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallContractResponse.ProtoReflect.Descriptor instead.
func (*CallContractResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_trader_proto_rawDescGZIP(), []int{10}
}

func (x *CallContractResponse) GetReturnData() []byte {
	if x != nil {
		return x.ReturnData
	}
	return nil
}

func (x *CallContractResponse) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *CallContractResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CallContractResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_grpc_trader_proto protoreflect.FileDescriptor

const file_api_grpc_trader_proto_rawDesc = "" +
	"\n" +
	"\x15api/grpc/trader.proto\x12\x04grpc\"\x91\x02\n" +
	"\x15SimulateBundleRequest\x12\"\n" +
	"\ftransactions\x18\x01 \x03(\fR\ftransactions\x12(\n" +
	"\rmin_timestamp\x18\x02 \x01(\x04H\x00R\fminTimestamp\x88\x01\x01\x12(\n" +
	"\rmax_timestamp\x18\x03 \x01(\x04H\x01R\fmaxTimestamp\x88\x01\x01\x12#\n" +
	"\rreverting_txs\x18\x04 \x03(\x05R\frevertingTxs\x12&\n" +
	"\ftarget_block\x18\x05 \x01(\x04H\x02R\vtargetBlock\x88\x01\x01B\x10\n" +
	"\x0e_min_timestampB\x10\n" +
	"\x0e_max_timestampB\x0f\n" +
	"\r_target_block\"\x99\x02\n" +
	"\x16SimulateBundleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bgas_used\x18\x02 \x01(\x04R\agasUsed\x12\x16\n" +
	"\x06profit\x18\x03 \x01(\fR\x06profit\x12)\n" +
	"\x10coinbase_balance\x18\x04 \x01(\fR\x0fcoinbaseBalance\x12&\n" +
	"\x0ffailed_tx_index\x18\x05 \x01(\x05R\rfailedTxIndex\x12&\n" +
	"\x0ffailed_tx_error\x18\x06 \x01(\tR\rfailedTxError\x127\n" +
	"\n" +
	"tx_results\x18\a \x03(\v2\x18.grpc.TxSimulationResultR\ttxResults\"\x82\x01\n" +
	"\x12TxSimulationResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bgas_used\x18\x02 \x01(\x04R\agasUsed\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12!\n" +
	"\freturn_value\x18\x04 \x01(\fR\vreturnValue\"\x8f\x02\n" +
	"\x13SubmitBundleRequest\x12\"\n" +
	"\ftransactions\x18\x01 \x03(\fR\ftransactions\x12(\n" +
	"\rmin_timestamp\x18\x02 \x01(\x04H\x00R\fminTimestamp\x88\x01\x01\x12(\n" +
	"\rmax_timestamp\x18\x03 \x01(\x04H\x01R\fmaxTimestamp\x88\x01\x01\x12#\n" +
	"\rreverting_txs\x18\x04 \x03(\x05R\frevertingTxs\x12&\n" +
	"\ftarget_block\x18\x05 \x01(\x04H\x02R\vtargetBlock\x88\x01\x01B\x10\n" +
	"\x0e_min_timestampB\x10\n" +
	"\x0e_max_timestampB\x0f\n" +
	"\r_target_block\"7\n" +
	"\x14SubmitBundleResponse\x12\x1f\n" +
	"\vbundle_hash\x18\x01 \x01(\fR\n" +
	"bundleHash\"\x83\x01\n" +
	"\x16GetStorageBatchRequest\x12\x1a\n" +
	"\bcontract\x18\x01 \x01(\fR\bcontract\x12\x14\n" +
	"\x05slots\x18\x02 \x03(\fR\x05slots\x12&\n" +
	"\fblock_number\x18\x03 \x01(\x04H\x00R\vblockNumber\x88\x01\x01B\x0f\n" +
	"\r_block_number\"1\n" +
	"\x17GetStorageBatchResponse\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06values\"Z\n" +
	"\x1dGetPendingTransactionsRequest\x12'\n" +
	"\rmin_gas_price\x18\x01 \x01(\x04H\x00R\vminGasPrice\x88\x01\x01B\x10\n" +
	"\x0e_min_gas_price\"D\n" +
	"\x1eGetPendingTransactionsResponse\x12\"\n" +
	"\ftransactions\x18\x01 \x03(\fR\ftransactions\"\xfa\x01\n" +
	"\x13CallContractRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\fR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\fR\x02to\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x15\n" +
	"\x03gas\x18\x04 \x01(\x04H\x00R\x03gas\x88\x01\x01\x12 \n" +
	"\tgas_price\x18\x05 \x01(\x04H\x01R\bgasPrice\x88\x01\x01\x12\x19\n" +
	"\x05value\x18\x06 \x01(\fH\x02R\x05value\x88\x01\x01\x12&\n" +
	"\fblock_number\x18\a \x01(\x04H\x03R\vblockNumber\x88\x01\x01B\x06\n" +
	"\x04_gasB\f\n" +
	"\n" +
	"_gas_priceB\b\n" +
	"\x06_valueB\x0f\n" +
	"\r_block_number\"\x82\x01\n" +
	"\x14CallContractResponse\x12\x1f\n" +
	"\vreturn_data\x18\x01 \x01(\fR\n" +
	"returnData\x12\x19\n" +
	"\bgas_used\x18\x02 \x01(\x04R\agasUsed\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2\x9f\x03\n" +
	"\rTraderService\x12K\n" +
	"\x0eSimulateBundle\x12\x1b.grpc.SimulateBundleRequest\x1a\x1c.grpc.SimulateBundleResponse\x12E\n" +
	"\fSubmitBundle\x12\x19.grpc.SubmitBundleRequest\x1a\x1a.grpc.SubmitBundleResponse\x12N\n" +
	"\x0fGetStorageBatch\x12\x1c.grpc.GetStorageBatchRequest\x1a\x1d.grpc.GetStorageBatchResponse\x12c\n" +
	"\x16GetPendingTransactions\x12#.grpc.GetPendingTransactionsRequest\x1a$.grpc.GetPendingTransactionsResponse\x12E\n" +
	"\fCallContract\x12\x19.grpc.CallContractRequest\x1a\x1a.grpc.CallContractResponseB*Z(github.com/ethereum/go-ethereum/api/grpcb\x06proto3"

var (
	file_api_grpc_trader_proto_rawDescOnce sync.Once
	file_api_grpc_trader_proto_rawDescData []byte
)

func file_api_grpc_trader_proto_rawDescGZIP() []byte {
	file_api_grpc_trader_proto_rawDescOnce.Do(func() {
		file_api_grpc_trader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_trader_proto_rawDesc), len(file_api_grpc_trader_proto_rawDesc)))
	})
	return file_api_grpc_trader_proto_rawDescData
}

var file_api_grpc_trader_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_grpc_trader_proto_goTypes = []any{
	(*SimulateBundleRequest)(nil),          // 0: grpc.SimulateBundleRequest
	(*SimulateBundleResponse)(nil),         // 1: grpc.SimulateBundleResponse
	(*TxSimulationResult)(nil),             // 2: grpc.TxSimulationResult
	(*SubmitBundleRequest)(nil),            // 3: grpc.SubmitBundleRequest
	(*SubmitBundleResponse)(nil),           // 4: grpc.SubmitBundleResponse
	(*GetStorageBatchRequest)(nil),         // 5: grpc.GetStorageBatchRequest
	(*GetStorageBatchResponse)(nil),        // 6: grpc.GetStorageBatchResponse
	(*GetPendingTransactionsRequest)(nil),  // 7: grpc.GetPendingTransactionsRequest
	(*GetPendingTransactionsResponse)(nil), // 8: grpc.GetPendingTransactionsResponse
	(*CallContractRequest)(nil),            // 9: grpc.CallContractRequest
	(*CallContractResponse)(nil),           // 10: grpc.CallContractResponse
}
var file_api_grpc_trader_proto_depIdxs = []int32{
	2,  // 0: grpc.SimulateBundleResponse.tx_results:type_name -> grpc.TxSimulationResult
	0,  // 1: grpc.TraderService.SimulateBundle:input_type -> grpc.SimulateBundleRequest
	3,  // 2: grpc.TraderService.SubmitBundle:input_type -> grpc.SubmitBundleRequest
	5,  // 3: grpc.TraderService.GetStorageBatch:input_type -> grpc.GetStorageBatchRequest
	7,  // 4: grpc.TraderService.GetPendingTransactions:input_type -> grpc.GetPendingTransactionsRequest
	9,  // 5: grpc.TraderService.CallContract:input_type -> grpc.CallContractRequest
	1,  // 6: grpc.TraderService.SimulateBundle:output_type -> grpc.SimulateBundleResponse
	4,  // 7: grpc.TraderService.SubmitBundle:output_type -> grpc.SubmitBundleResponse
	6,  // 8: grpc.TraderService.GetStorageBatch:output_type -> grpc.GetStorageBatchResponse
	8,  // 9: grpc.TraderService.GetPendingTransactions:output_type -> grpc.GetPendingTransactionsResponse
	10, // 10: grpc.TraderService.CallContract:output_type -> grpc.CallContractResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_grpc_trader_proto_init() }
func file_api_grpc_trader_proto_init() {
	if File_api_grpc_trader_proto != nil {
		return
	}
	file_api_grpc_trader_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_grpc_trader_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_grpc_trader_proto_msgTypes[5].OneofWrappers = []any{}
	file_api_grpc_trader_proto_msgTypes[7].OneofWrappers = []any{}
	file_api_grpc_trader_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_trader_proto_rawDesc), len(file_api_grpc_trader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_trader_proto_goTypes,
		DependencyIndexes: file_api_grpc_trader_proto_depIdxs,
		MessageInfos:      file_api_grpc_trader_proto_msgTypes,
	}.Build()
	File_api_grpc_trader_proto = out.File
	file_api_grpc_trader_proto_goTypes = nil
	file_api_grpc_trader_proto_depIdxs = nil
}
