// Copyright 2026 The go-ethereum Authors
// This file is part of the go-ethereum library.
//
// The go-ethereum library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The go-ethereum library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the go-ethereum library. If not, see <http://www.gnu.org/licenses/>.

// Whole-contract interpreter benchmarks from the evm-bench suite
// (github.com/ziyadedher/evm-bench). Each contract exposes a Benchmark()
// entrypoint (selector 0x30627b7c) that performs the whole workload internally
// (e.g. 5000 mints), so the benchmark is a single Call per iteration. These
// complement the opcode/loop micro-benchmarks in runtime_test.go with realistic
// workloads (a ray tracer, ERC-20 transfer/mint/approval, a hashing loop) and
// use the same names as evm-bench / gevm for cross-comparison.
//
// Run:           go test ./core/vm/runtime/ -run '^$' -bench 'Benchmark(Snailtracer|TenThousandHashes|ERC20)' -benchmem -count=10
// Compare A/B:   ./core/vm/runtime/testdata/evm-bench/compare.sh
//
// The committed runtime bytecode in testdata/*.hex is regenerated by
// testdata/evm-bench/gen.sh (solc via docker). See that script for provenance
// and exact compiler versions.

package runtime

import (
	_ "embed"
	"encoding/hex"
	"strings"
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/state"
	"github.com/ethereum/go-ethereum/core/tracing"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/holiman/uint256"
)

//go:embed testdata/snailtracer.hex
var benchSnailtracerHex string

//go:embed testdata/tenthousandhashes.hex
var benchTenThousandHashesHex string

//go:embed testdata/erc20transfer.hex
var benchERC20TransferHex string

//go:embed testdata/erc20mint.hex
var benchERC20MintHex string

//go:embed testdata/erc20approval.hex
var benchERC20ApprovalHex string

// benchmarkSelector is keccak256("Benchmark()")[:4], the evm-bench entrypoint.
var benchmarkSelector = []byte{0x30, 0x62, 0x7b, 0x7c}

func benchHexToBytes(s string) []byte {
	b, err := hex.DecodeString(strings.TrimSpace(s))
	if err != nil {
		panic(err)
	}
	return b
}

// runEVMBench deploys the contract's runtime bytecode and repeatedly invokes its
// Benchmark() entrypoint. The contract's constructor is not run, so storage
// starts empty. The evm-bench contracts set up whatever state they need inside
// Benchmark(), which matches the work the evm-bench harness measures.
func runEVMBench(b *testing.B, codeHex string) {
	code := benchHexToBytes(codeHex)
	statedb, err := state.New(types.EmptyRootHash, state.NewDatabaseForTesting())
	if err != nil {
		b.Fatal(err)
	}
	contract := common.BytesToAddress([]byte{0x10})
	caller := common.BytesToAddress([]byte{0x01})
	statedb.CreateAccount(caller)
	statedb.AddBalance(caller, uint256.NewInt(1_000_000_000), tracing.BalanceChangeUnspecified)
	statedb.SetCode(contract, code, tracing.CodeChangeUnspecified)

	cfg := &Config{Origin: caller, State: statedb, GasLimit: 10_000_000_000}

	// Sanity: the workload must run to completion, not revert/out-of-gas.
	if _, _, err := Call(contract, benchmarkSelector, cfg); err != nil {
		b.Fatalf("Benchmark() did not complete: %v", err)
	}
	b.ReportAllocs()
	b.ResetTimer()
	for b.Loop() {
		Call(contract, benchmarkSelector, cfg)
	}
}

func BenchmarkSnailtracer(b *testing.B)           { runEVMBench(b, benchSnailtracerHex) }
func BenchmarkTenThousandHashes(b *testing.B)     { runEVMBench(b, benchTenThousandHashesHex) }
func BenchmarkERC20Transfer(b *testing.B)         { runEVMBench(b, benchERC20TransferHex) }
func BenchmarkERC20Mint(b *testing.B)             { runEVMBench(b, benchERC20MintHex) }
func BenchmarkERC20ApprovalTransfer(b *testing.B) { runEVMBench(b, benchERC20ApprovalHex) }
