name: Build and Push to Google Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    if: contains(github.event.head_commit.message, 'CI:Build')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_KEY }}'

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker europe-west3-docker.pkg.dev

      - name: Build and Push to Artifact Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: europe-west3-docker.pkg.dev/task-460410/task-repo/app:latest
