name: Build Docker Image
on:
  pull_request:
    types:
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: yohands/devops_task:pr-${{ github.event.pull_request.number }}
          labels: type=pr,event=merge
    env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
