name: Test and build

on:
  push:
    branches:
      - '**'

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.16 ]
        platform: [ ubuntu-latest ]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          go get -v -t -d ./...

      - name: Lint
        run: go run ./build/ci.go lint

      - name: Test
        run: SKIP_ANDROID=true go run ./build/ci.go test

  build:
    strategy:
      matrix:
        go-version: [ 1.16 ]
#         Add additional platforms here if we need more
#        This should assure that we have buildable artifact
        platform: [ ubuntu-latest ]

    runs-on: ${{ matrix.platform }}

    needs: [ test ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout submodules
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Install dependencies
        run: |
          go get -v -t -d ./...

      - name: Run build
        run: go run ./build/ci.go install
