name: CI-Build

on:
  pull_request:
    types: [closed]
    branches: ["master"]

jobs:
  build-docker-image:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'CI:Build')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}   # Ensure your Docker Hub username is stored as a secret
          password: ${{ secrets.DOCKERHUB_TOKEN }}      # Ensure your Docker Hub token is stored as a secret

      - name: Build and push Docker image to Docker Hub Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: user/app:latest  # Replace 'user/app' with your Docker Hub repository name
